/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaNanoSerenade;


import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author aliay
 */
public class ManagePeopleForm extends javax.swing.JFrame {

    /**
     * Creates new form ManageRoomsForm
     */
    
    PEOPLE people = new PEOPLE();
    
    public ManagePeopleForm() {
        initComponents();
        
         //ajout d une icone serende pour la page
          this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/javaNanoSerenade/image/lloogg_ser.png")).getImage());
        
        //populate the jtable
        people.fillPeopleJTable(jTable1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldPeopleID = new javax.swing.JTextField();
        jLabel52 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabelNote = new javax.swing.JLabel();
        jTextFieldLName = new javax.swing.JTextField();
        jTextFieldFName = new javax.swing.JTextField();
        jTextFieldMName = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabelNote1 = new javax.swing.JLabel();
        jTextFieldWeb = new javax.swing.JTextField();
        jLabelNote2 = new javax.swing.JLabel();
        jTextFieldPhone = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonAddPeople = new javax.swing.JButton();
        jButtonRemovePeople = new javax.swing.JButton();
        jButtonEditPeople = new javax.swing.JButton();
        jButtonClearPeople = new javax.swing.JButton();
        jButtonRefreshPeople = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenu4 = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manage People");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setName(""); // NOI18N

        jPanel10.setBackground(new java.awt.Color(204, 204, 204));
        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.MatteBorder(null), "People informations", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 16))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel9.setText("People ID:");

        jTextFieldPeopleID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldPeopleID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPeopleIDActionPerformed(evt);
            }
        });

        jLabel57.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel11.setText("First Name:");

        jLabelNote.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabelNote.setText("Last Name:");

        jTextFieldLName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTextFieldFName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldFName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFNameActionPerformed(evt);
            }
        });

        jTextFieldMName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldMName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMNameActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel14.setText("Middle Name:");

        jLabel16.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel16.setText("Email:");

        jTextFieldEmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEmailActionPerformed(evt);
            }
        });

        jLabelNote1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabelNote1.setText("Web:");

        jTextFieldWeb.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldWeb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldWebActionPerformed(evt);
            }
        });

        jLabelNote2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabelNote2.setText("Phone:");

        jTextFieldPhone.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPhoneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel57)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel58)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel52))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(150, 150, 150)
                        .addComponent(jLabelNote2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelNote1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldWeb, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100))))
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldPeopleID, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldFName, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jLabelNote)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldLName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldMName, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 21, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPeopleID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11)
                    .addComponent(jTextFieldFName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldLName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNote, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldMName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNote1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldWeb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addComponent(jLabel52))
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16))
                    .addComponent(jLabelNote2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel57)
                    .addComponent(jLabel58)))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "People ID", "First Name", "Last Name", "Middle Name", "Email", "Phone", "Web"
            }
        )
        //make the jtable cell not editable
        {public boolean isCellEditable(int row, int column){return false;}}
    );
    jTable1.setGridColor(new java.awt.Color(204, 255, 0));

    jTable1.setSelectionBackground(new java.awt.Color(0, 153, 0));
    jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jTable1MouseClicked(evt);
        }
    });
    jScrollPane1.setViewportView(jTable1);

    jButtonAddPeople.setBackground(new java.awt.Color(204, 204, 204));
    jButtonAddPeople.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
    jButtonAddPeople.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaNanoSerenade/image/save_button.png"))); // NOI18N
    jButtonAddPeople.setBorderPainted(false);
    jButtonAddPeople.setContentAreaFilled(false);
    jButtonAddPeople.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jButtonAddPeople.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonAddPeopleActionPerformed(evt);
        }
    });

    jButtonRemovePeople.setBackground(new java.awt.Color(204, 204, 204));
    jButtonRemovePeople.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
    jButtonRemovePeople.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaNanoSerenade/image/remove_button.png"))); // NOI18N
    jButtonRemovePeople.setBorderPainted(false);
    jButtonRemovePeople.setContentAreaFilled(false);
    jButtonRemovePeople.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jButtonRemovePeople.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonRemovePeopleActionPerformed(evt);
        }
    });

    jButtonEditPeople.setBackground(new java.awt.Color(204, 204, 204));
    jButtonEditPeople.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
    jButtonEditPeople.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaNanoSerenade/image/edit_button.png"))); // NOI18N
    jButtonEditPeople.setBorderPainted(false);
    jButtonEditPeople.setContentAreaFilled(false);
    jButtonEditPeople.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jButtonEditPeople.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonEditPeopleActionPerformed(evt);
        }
    });

    jButtonClearPeople.setBackground(new java.awt.Color(204, 204, 204));
    jButtonClearPeople.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
    jButtonClearPeople.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaNanoSerenade/image/reset_button.png"))); // NOI18N
    jButtonClearPeople.setBorderPainted(false);
    jButtonClearPeople.setContentAreaFilled(false);
    jButtonClearPeople.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jButtonClearPeople.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonClearPeopleActionPerformed(evt);
        }
    });

    jButtonRefreshPeople.setBackground(new java.awt.Color(204, 204, 204));
    jButtonRefreshPeople.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
    jButtonRefreshPeople.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaNanoSerenade/image/refresh_button.png"))); // NOI18N
    jButtonRefreshPeople.setBorderPainted(false);
    jButtonRefreshPeople.setContentAreaFilled(false);
    jButtonRefreshPeople.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jButtonRefreshPeople.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonRefreshPeopleActionPerformed(evt);
        }
    });

    jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaNanoSerenade/image/exit_button.png"))); // NOI18N
    jButton1.setBorderPainted(false);
    jButton1.setContentAreaFilled(false);
    jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jButton1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton1ActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(42, 42, 42)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jButtonAddPeople, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(71, 71, 71)
                            .addComponent(jButtonEditPeople, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(68, 68, 68)
                            .addComponent(jButtonRemovePeople, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(72, 72, 72)
                            .addComponent(jButtonClearPeople, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(68, 68, 68)
                            .addComponent(jButtonRefreshPeople, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addContainerGap())
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jButtonClearPeople, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButtonRefreshPeople)
                .addComponent(jButtonEditPeople)
                .addComponent(jButtonRemovePeople)
                .addComponent(jButtonAddPeople)
                .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(81, Short.MAX_VALUE))
    );

    jMenu1.setText("File");
    jMenuBar1.add(jMenu1);

    jMenu2.setText("Edit");
    jMenuBar1.add(jMenu2);

    jMenu3.setText("Help");

    jMenu5.setText("Tutorial");
    jMenu3.add(jMenu5);
    jMenu3.add(jSeparator1);

    jMenu4.setText("About the SERENADE");
    jMenu3.add(jMenu4);

    jMenuBar1.add(jMenu3);

    setJMenuBar(jMenuBar1);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, 0))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldPeopleIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPeopleIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPeopleIDActionPerformed

    private void jTextFieldFNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFNameActionPerformed

    private void jTextFieldMNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMNameActionPerformed

    private void jTextFieldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmailActionPerformed

    private void jTextFieldWebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldWebActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldWebActionPerformed

    private void jButtonAddPeopleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddPeopleActionPerformed
        
       //get data from jtextfields
       
            String fname = jTextFieldFName.getText();
            String lname = jTextFieldLName.getText();        
            String mname = jTextFieldMName.getText();
            String email = jTextFieldEmail.getText();
            String phone = jTextFieldPhone.getText();
            String web = jTextFieldWeb.getText();
            
         if(fname.trim().equals("") || lname.trim().equals("") || mname.trim().equals("") || email.trim().equals("") || phone.trim().equals("") || web.trim().equals(""))
        {
            JOptionPane.showMessageDialog(rootPane, "Required Fields -> First, Laste and Middle Names + Email + Phone + Web.", "Empty Fields", JOptionPane.WARNING_MESSAGE);
        }
        else {
            if(people.addPeople(fname, lname, mname, email, phone, web))
            {
                JOptionPane.showMessageDialog(rootPane, "New People added Successfully", "Add People", JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(rootPane, "People Not Added ", "Add People Error", JOptionPane.ERROR_MESSAGE);
            }
         }
         //clear the JTable first
       jTable1.setModel(new DefaultTableModel(null, new Object[]{"People ID", "First Name", "Last Name", "Middle Name", "Email", "Phone", "Web"}));
       
        // then populate the JTable
        people.fillPeopleJTable(jTable1);
    }//GEN-LAST:event_jButtonAddPeopleActionPerformed
private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {                                     
        //display the selected row data in the jtextfields
        
        //get the jlabel model 
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                
        // get the selected row index
        int rIndex = jTable1.getSelectedRow();
        
        //display data 
        jTextFieldPeopleID.setText(model.getValueAt(rIndex, 0).toString());
        jTextFieldFName.setText(model.getValueAt(rIndex, 1).toString());
        jTextFieldLName.setText(model.getValueAt(rIndex, 2).toString());
        jTextFieldMName.setText(model.getValueAt(rIndex, 3).toString());
        jTextFieldEmail.setText(model.getValueAt(rIndex, 4).toString());
        jTextFieldPhone.setText(model.getValueAt(rIndex, 5).toString());
        jTextFieldWeb.setText(model.getValueAt(rIndex, 6).toString());
    }                             

    private void jButtonClearPeopleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearPeopleActionPerformed
        // remove text from all jTextfields
        jTextFieldEmail.setText("");
        jTextFieldMName.setText("");
        jTextFieldLName.setText("");
        jTextFieldPeopleID.setText("");
        jTextFieldFName.setText("");
        jTextFieldWeb.setText("");
        jTextFieldPhone.setText("");
        
    }//GEN-LAST:event_jButtonClearPeopleActionPerformed

    private void jButtonRefreshPeopleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefreshPeopleActionPerformed
         //clear the JTable first
       jTable1.setModel(new DefaultTableModel(null, new Object[]{"People ID", "First Name", "Last Name", "Middle Name", "Email", "Phone", "Web"}));
       
        // then populate the JTable
        people.fillPeopleJTable(jTable1);
    }//GEN-LAST:event_jButtonRefreshPeopleActionPerformed

    private void jButtonEditPeopleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditPeopleActionPerformed
         // EDIT THE SELECTED CLIENT
        
        //get data from the fields
    try{
        int peopleID = Integer.valueOf(jTextFieldPeopleID.getText());;
        String fname = jTextFieldFName.getText();
        String lname = jTextFieldLName.getText();        
        String mname = jTextFieldMName.getText();
        String email = jTextFieldEmail.getText();
        String phone = jTextFieldPhone.getText();
        String web = jTextFieldWeb.getText();
        
          
                      
         if(people.editPeople(peopleID, fname, lname, mname, email, phone, web))
            {
                JOptionPane.showMessageDialog(rootPane, "People Data Updated Successfully", "Edit People", JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(rootPane, "People Data Not Updated ", "Edit People Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch(NumberFormatException ex)
              {
                JOptionPane.showMessageDialog(rootPane, ex.getMessage() + "Enter The People ID", "People ID Error", JOptionPane.ERROR_MESSAGE);
            }
   
            //clear the JTable first
       jTable1.setModel(new DefaultTableModel(null, new Object[]{"People ID", "First Name", "Last Name", "Middle Name", "Email", "Phone", "Web"}));
       
        // then populate the JTable
        people.fillPeopleJTable(jTable1);   
          
          
    }//GEN-LAST:event_jButtonEditPeopleActionPerformed

    private void jButtonRemovePeopleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemovePeopleActionPerformed
         try{
                    int peopleID = Integer.valueOf(jTextFieldPeopleID.getText());
                    
                    if(people.removePeople(peopleID))
                        {
                            JOptionPane.showMessageDialog(rootPane, "People Deleted Successfully", "Remove Protocol", JOptionPane.INFORMATION_MESSAGE);
                    }
                    else{
                            JOptionPane.showMessageDialog(rootPane, "People Not Deleted ", "Remove Protocol Error", JOptionPane.ERROR_MESSAGE);
                        }
               }
              catch(NumberFormatException ex)
              {
                JOptionPane.showMessageDialog(rootPane, ex.getMessage() + "Enter The People Id ", "People ID Error", JOptionPane.ERROR_MESSAGE);
            }
         //clear the JTable first
       jTable1.setModel(new DefaultTableModel(null, new Object[]{"People ID", "First Name", "Last Name", "Middle Name", "Email", "Phone", "Web"}));
       
        // then populate the JTable
        people.fillPeopleJTable(jTable1);
    }//GEN-LAST:event_jButtonRemovePeopleActionPerformed

    private void jTextFieldPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPhoneActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagePeopleForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagePeopleForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagePeopleForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagePeopleForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagePeopleForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAddPeople;
    private javax.swing.JButton jButtonClearPeople;
    private javax.swing.JButton jButtonEditPeople;
    private javax.swing.JButton jButtonRefreshPeople;
    private javax.swing.JButton jButtonRemovePeople;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelNote;
    private javax.swing.JLabel jLabelNote1;
    private javax.swing.JLabel jLabelNote2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldFName;
    private javax.swing.JTextField jTextFieldLName;
    private javax.swing.JTextField jTextFieldMName;
    private javax.swing.JTextField jTextFieldPeopleID;
    private javax.swing.JTextField jTextFieldPhone;
    private javax.swing.JTextField jTextFieldWeb;
    // End of variables declaration//GEN-END:variables
}
