/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaNanoSerenade;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aliay
 */
public class ManageInstrumentForm extends javax.swing.JFrame {

    INSTRUMENT instrument = new INSTRUMENT();
    
    /**
     * Creates new form ManageRoomsForm
     */
    public ManageInstrumentForm() {
        initComponents();
        
         //ajout d une icone serende pour la page
          this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/javaNanoSerenade/image/lloogg_ser.png")).getImage());
        
        //populate the jtable
        instrument.fillInstrumentJTable(jTable1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldInstrumentID = new javax.swing.JTextField();
        jLabel52 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabelNote = new javax.swing.JLabel();
        jTextFieldModel = new javax.swing.JTextField();
        jTextFieldInstrumentName = new javax.swing.JTextField();
        jTextFieldManName = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldManCity = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldManState = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldManCountry = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonRefreshInstrument = new javax.swing.JButton();
        jButtonClearInstrument = new javax.swing.JButton();
        jButtonEditInstrument = new javax.swing.JButton();
        jButtonRemoveInstrument = new javax.swing.JButton();
        jButtonAddInstrument = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenu4 = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manage Instrument");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setName(""); // NOI18N

        jPanel10.setBackground(new java.awt.Color(204, 204, 204));
        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.MatteBorder(null), "Instrument informations", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 16))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel9.setText("Instrument ID:");

        jTextFieldInstrumentID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldInstrumentID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldInstrumentIDActionPerformed(evt);
            }
        });

        jLabel57.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel11.setText("Instrument Name:");

        jLabelNote.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabelNote.setText("Model:");

        jTextFieldModel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldModel.setMinimumSize(new java.awt.Dimension(6, 20));

        jTextFieldInstrumentName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldInstrumentName.setMinimumSize(new java.awt.Dimension(6, 20));
        jTextFieldInstrumentName.setPreferredSize(new java.awt.Dimension(6, 25));
        jTextFieldInstrumentName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldInstrumentNameActionPerformed(evt);
            }
        });

        jTextFieldManName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldManName.setMinimumSize(new java.awt.Dimension(6, 20));
        jTextFieldManName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldManNameActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel10.setText("Manufacturer Name:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel12.setText("Manufacturer City:");

        jTextFieldManCity.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldManCity.setMinimumSize(new java.awt.Dimension(6, 20));
        jTextFieldManCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldManCityActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel13.setText("Manufacturer State:");

        jTextFieldManState.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldManState.setMinimumSize(new java.awt.Dimension(6, 20));
        jTextFieldManState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldManStateActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel15.setText("Manufacturer Country:");

        jTextFieldManCountry.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldManCountry.setMinimumSize(new java.awt.Dimension(6, 20));
        jTextFieldManCountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldManCountryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jLabel57)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel58)
                .addGap(45, 45, 45)
                .addComponent(jLabel52))
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldManCity, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldManState, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldManCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldInstrumentID, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldInstrumentName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelNote)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldModel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldManName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldManName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10))
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldInstrumentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11)
                        .addComponent(jTextFieldModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelNote, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldInstrumentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldManCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jTextFieldManState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jTextFieldManCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel52)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel57)
                    .addComponent(jLabel58)))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Instrument ID", "Name", "Model", "Manufacturer Name", "Manufacturer City", "Manufacturer State", "Manufacturer Country"
            }
        )//make the jtable cell not editable
        {public boolean isCellEditable(int row, int column){return false;}}
    );
    jTable1.setGridColor(new java.awt.Color(204, 255, 0));

    jTable1.setSelectionBackground(new java.awt.Color(0, 153, 0));

    jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jTable1MouseClicked(evt);
        }
    });
    jScrollPane1.setViewportView(jTable1);

    jButtonRefreshInstrument.setBackground(new java.awt.Color(204, 204, 204));
    jButtonRefreshInstrument.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
    jButtonRefreshInstrument.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaNanoSerenade/image/refresh_button.png"))); // NOI18N
    jButtonRefreshInstrument.setBorderPainted(false);
    jButtonRefreshInstrument.setContentAreaFilled(false);
    jButtonRefreshInstrument.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jButtonRefreshInstrument.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonRefreshInstrumentActionPerformed(evt);
        }
    });

    jButtonClearInstrument.setBackground(new java.awt.Color(204, 204, 204));
    jButtonClearInstrument.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
    jButtonClearInstrument.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaNanoSerenade/image/reset_button.png"))); // NOI18N
    jButtonClearInstrument.setBorderPainted(false);
    jButtonClearInstrument.setContentAreaFilled(false);
    jButtonClearInstrument.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jButtonClearInstrument.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonClearInstrumentActionPerformed(evt);
        }
    });

    jButtonEditInstrument.setBackground(new java.awt.Color(204, 204, 204));
    jButtonEditInstrument.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
    jButtonEditInstrument.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaNanoSerenade/image/edit_button.png"))); // NOI18N
    jButtonEditInstrument.setBorderPainted(false);
    jButtonEditInstrument.setContentAreaFilled(false);
    jButtonEditInstrument.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jButtonEditInstrument.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonEditInstrumentActionPerformed(evt);
        }
    });

    jButtonRemoveInstrument.setBackground(new java.awt.Color(204, 204, 204));
    jButtonRemoveInstrument.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
    jButtonRemoveInstrument.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaNanoSerenade/image/remove_button.png"))); // NOI18N
    jButtonRemoveInstrument.setBorderPainted(false);
    jButtonRemoveInstrument.setContentAreaFilled(false);
    jButtonRemoveInstrument.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jButtonRemoveInstrument.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonRemoveInstrumentActionPerformed(evt);
        }
    });

    jButtonAddInstrument.setBackground(new java.awt.Color(204, 204, 204));
    jButtonAddInstrument.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
    jButtonAddInstrument.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaNanoSerenade/image/save_button.png"))); // NOI18N
    jButtonAddInstrument.setBorderPainted(false);
    jButtonAddInstrument.setContentAreaFilled(false);
    jButtonAddInstrument.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jButtonAddInstrument.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonAddInstrumentActionPerformed(evt);
        }
    });

    jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaNanoSerenade/image/exit_button.png"))); // NOI18N
    jButton1.setBorderPainted(false);
    jButton1.setContentAreaFilled(false);
    jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jButton1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton1ActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(24, 24, 24)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1235, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 1270, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(66, 66, 66)
                    .addComponent(jButtonAddInstrument, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(66, 66, 66)
                    .addComponent(jButtonRemoveInstrument, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(75, 75, 75)
                    .addComponent(jButtonEditInstrument, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(71, 71, 71)
                    .addComponent(jButtonClearInstrument, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(67, 67, 67)
                    .addComponent(jButtonRefreshInstrument, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(78, 78, 78)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGap(8, 15, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonRefreshInstrument)
                    .addComponent(jButtonClearInstrument, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonRemoveInstrument)
                    .addComponent(jButtonEditInstrument)
                    .addComponent(jButtonAddInstrument))
                .addComponent(jButton1))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(24, Short.MAX_VALUE))
    );

    jMenu1.setText("File");
    jMenuBar1.add(jMenu1);

    jMenu2.setText("Edit");
    jMenuBar1.add(jMenu2);

    jMenu3.setText("Help");

    jMenu5.setText("Tutorial");
    jMenu3.add(jMenu5);
    jMenu3.add(jSeparator1);

    jMenu4.setText("About the SERENADE");
    jMenu3.add(jMenu4);

    jMenuBar1.add(jMenu3);

    setJMenuBar(jMenuBar1);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldInstrumentIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldInstrumentIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldInstrumentIDActionPerformed

    private void jTextFieldInstrumentNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldInstrumentNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldInstrumentNameActionPerformed

    private void jTextFieldManNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldManNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldManNameActionPerformed

    private void jTextFieldManCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldManCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldManCityActionPerformed

    private void jTextFieldManStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldManStateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldManStateActionPerformed

    private void jTextFieldManCountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldManCountryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldManCountryActionPerformed

    private void jButtonAddInstrumentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddInstrumentActionPerformed
        //add a new cient
        
        //get data from the fields
        String name = jTextFieldInstrumentName.getText();
        String model = jTextFieldModel.getText();
        String manufacturer_name = jTextFieldManName.getText();
        String manufacturer_city = jTextFieldManCity.getText();
        String manufacturer_state = jTextFieldManState.getText();
        String manufacturer_coutry = jTextFieldManCountry.getText();
        
        if(name.trim().equals("") || model.trim().equals("") || manufacturer_name.trim().equals("") || manufacturer_city.trim().equals("") || manufacturer_state.trim().equals("") || manufacturer_coutry.trim().equals(""))
        {
            JOptionPane.showMessageDialog(rootPane, "Required Fields -> First/Last Name + The Phone Number + The Email.", "Empty Fields", JOptionPane.WARNING_MESSAGE);
        }
        else {
            if(instrument.addInstrument(name, model, manufacturer_name, manufacturer_city, manufacturer_state, manufacturer_coutry))
            {
                JOptionPane.showMessageDialog(rootPane, "New Client added Successfully", "Add Client", JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(rootPane, "Client Not Added ", "Add Client Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        //clear the JTable first
       jTable1.setModel(new DefaultTableModel(null, new Object[]{"Instrument ID", "Name", "Model", "Manufacturer Name", "Manufacturer City", "Manufacturer State", "Manufacturer Country"}));
       
        // then populate the JTable
        instrument.fillInstrumentJTable(jTable1);
    }//GEN-LAST:event_jButtonAddInstrumentActionPerformed
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {                                     
        //display the selected row data in the jtextfields
        
        //get the jlabel model 
        DefaultTableModel model = (DefaultTableModel )jTable1.getModel();
                
        // get the selected row index
        int rIndex = jTable1.getSelectedRow();
        
        //display data 
        jTextFieldInstrumentID.setText(model.getValueAt(rIndex, 0).toString());
        jTextFieldInstrumentName.setText(model.getValueAt(rIndex, 1).toString());
        jTextFieldModel.setText(model.getValueAt(rIndex, 2).toString());
        jTextFieldManName.setText(model.getValueAt(rIndex, 3).toString());
        jTextFieldManCity.setText(model.getValueAt(rIndex, 4).toString());
        jTextFieldManState.setText(model.getValueAt(rIndex, 5).toString());
        jTextFieldManCountry.setText(model.getValueAt(rIndex, 6).toString());
    }                                
    private void jButtonClearInstrumentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearInstrumentActionPerformed
        // remove text from all jTextfields
        jTextFieldInstrumentID.setText("");
        jTextFieldInstrumentName.setText("");
        jTextFieldManCity.setText("");
        jTextFieldManCountry.setText("");
        jTextFieldManName.setText("");
        jTextFieldManState.setText("");
        jTextFieldModel.setText("");
    }//GEN-LAST:event_jButtonClearInstrumentActionPerformed

    private void jButtonRefreshInstrumentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefreshInstrumentActionPerformed
         //clear the JTable first
       jTable1.setModel(new DefaultTableModel(null, new Object[]{"Instrument ID", "Name", "Model", "Manufacturer Name", "Manufacturer City", "Manufacturer State", "Manufacturer Country"}));
       
        // then populate the JTable
        instrument.fillInstrumentJTable(jTable1);
    }//GEN-LAST:event_jButtonRefreshInstrumentActionPerformed

    private void jButtonRemoveInstrumentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveInstrumentActionPerformed
         // Delete the selected client
        try{
                    int instrumentID = Integer.valueOf(jTextFieldInstrumentID.getText());
                    
                    if(instrument.removeInstrument(instrumentID))
                        {
                            JOptionPane.showMessageDialog(rootPane, "Instrument Deleted Successfully", "Remove Instrument", JOptionPane.INFORMATION_MESSAGE);
                    }
                    else{
                            JOptionPane.showMessageDialog(rootPane, "Instrument Not Deleted ", "Remove Instrument Error", JOptionPane.ERROR_MESSAGE);
                        }
               }
              catch(NumberFormatException ex)
              {
                JOptionPane.showMessageDialog(rootPane, ex.getMessage() + "Enter The Instrument Id ", "Instrument ID Error", JOptionPane.ERROR_MESSAGE);
            }
        //clear the JTable first
       jTable1.setModel(new DefaultTableModel(null, new Object[]{"Instrument ID", "Name", "Model", "Manufacturer Name", "Manufacturer City", "Manufacturer State", "Manufacturer Country"}));
       
        // then populate the JTable
        instrument.fillInstrumentJTable(jTable1);
    }//GEN-LAST:event_jButtonRemoveInstrumentActionPerformed

    private void jButtonEditInstrumentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditInstrumentActionPerformed
         // EDIT THE SELECTED CLIENT
        
        //get data from the fields
        int instrumentID = 0;
        String name = jTextFieldInstrumentName.getText();
        String model = jTextFieldModel.getText();
        String manufacturer_name = jTextFieldManName.getText();
        String manufacturer_city = jTextFieldManCity.getText();
        String manufacturer_state = jTextFieldManState.getText();
        String manufacturer_coutry = jTextFieldManCountry.getText();
        
          if(name.trim().equals("") || model.trim().equals("") || manufacturer_name.trim().equals("") || manufacturer_city.trim().equals("") || manufacturer_state.trim().equals("") || manufacturer_coutry.trim().equals(""))
        {
            JOptionPane.showMessageDialog(rootPane, "Required Fields -> Name + Model + Manufacturer Name, City, State and Country.", "Empty Fields", JOptionPane.WARNING_MESSAGE);
        }
        else {
              
              try{
                    instrumentID = Integer.valueOf(jTextFieldInstrumentID.getText());
                    
                    if(instrument.editInstrument(instrumentID, name, model, manufacturer_name, manufacturer_city, manufacturer_state, manufacturer_coutry))
                        {
                            JOptionPane.showMessageDialog(rootPane, "Instrument Data Updated Successfully", "Edit Instrument", JOptionPane.INFORMATION_MESSAGE);
                    }else{
                            JOptionPane.showMessageDialog(rootPane, "Instrument Data Not Updated ", "Edit Instrument Error", JOptionPane.ERROR_MESSAGE);
                        }
               }
              catch(NumberFormatException ex)
              {
                JOptionPane.showMessageDialog(rootPane, ex.getMessage() + "Enter The Instrument Id ", "Instrument ID Error", JOptionPane.ERROR_MESSAGE);
            }
          }
          //clear the JTable first
       jTable1.setModel(new DefaultTableModel(null, new Object[]{"Instrument ID", "Name", "Model", "Manufacturer Name", "Manufacturer City", "Manufacturer State", "Manufacturer Country"}));
       
        // then populate the JTable
        instrument.fillInstrumentJTable(jTable1);
    }//GEN-LAST:event_jButtonEditInstrumentActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageInstrumentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageInstrumentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageInstrumentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageInstrumentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageInstrumentForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAddInstrument;
    private javax.swing.JButton jButtonClearInstrument;
    private javax.swing.JButton jButtonEditInstrument;
    private javax.swing.JButton jButtonRefreshInstrument;
    private javax.swing.JButton jButtonRemoveInstrument;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelNote;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldInstrumentID;
    private javax.swing.JTextField jTextFieldInstrumentName;
    private javax.swing.JTextField jTextFieldManCity;
    private javax.swing.JTextField jTextFieldManCountry;
    private javax.swing.JTextField jTextFieldManName;
    private javax.swing.JTextField jTextFieldManState;
    private javax.swing.JTextField jTextFieldModel;
    // End of variables declaration//GEN-END:variables
}
