/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaNanoSerenade;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author aliay
 */
public class ManagePublicationForm extends javax.swing.JFrame {

        PUBLICATION publication = new PUBLICATION();

    /**
     * Creates new form ManageRoomsForm
     */
    public ManagePublicationForm() {
        initComponents();
        
         //ajout d une icone serende pour la page
          this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/javaNanoSerenade/image/lloogg_ser.png")).getImage());
        
         //populate the jtable
        publication.fillPublicationJTable(jTable1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jTextFieldJournal = new javax.swing.JTextField();
        jTextFieldTitle = new javax.swing.JTextField();
        jTextFieldDOI = new javax.swing.JTextField();
        jLabel52 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jTextFieldIssue = new javax.swing.JTextField();
        jTextFieldYear = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldVolume = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jTextFieldCurationStatus = new javax.swing.JTextField();
        jTextFieldPublishStatus = new javax.swing.JTextField();
        jTextFieldAbstract = new javax.swing.JTextField();
        jTextFieldKeywords = new javax.swing.JTextField();
        jTextFieldContact = new javax.swing.JTextField();
        jTextFieldPage = new javax.swing.JTextField();
        jTextFieldCurationNote = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonAddPublication = new javax.swing.JButton();
        jButtonRemovePublication = new javax.swing.JButton();
        jButtonEditPublication = new javax.swing.JButton();
        jButtonClearPublication = new javax.swing.JButton();
        jButtonRefreshPublication = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenu4 = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manage Publication");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setName(""); // NOI18N

        jPanel10.setBackground(new java.awt.Color(204, 204, 204));
        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.MatteBorder(null), "Publication informations", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 16))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel9.setText("Doi:");

        jLabel31.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel31.setText("Title:");

        jLabel32.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel32.setText("Journal:");

        jTextFieldJournal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTextFieldTitle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTextFieldDOI.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldDOI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDOIActionPerformed(evt);
            }
        });

        jLabel37.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel37.setText("Issue:");

        jTextFieldIssue.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTextFieldYear.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel10.setText("Year:");

        jLabel54.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel54.setText("Page:");

        jLabel57.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel12.setText("Volume:");

        jTextFieldVolume.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel11.setText("Contact Author:");

        jLabel38.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel38.setText("Keywords:");

        jLabel45.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel45.setText("Abstract:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel14.setText("Publish Status:");

        jLabel15.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel15.setText("Curation Status:");

        jLabel46.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel46.setText("Curation Note:");

        jTextFieldCurationStatus.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTextFieldPublishStatus.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTextFieldAbstract.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldAbstract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAbstractActionPerformed(evt);
            }
        });

        jTextFieldKeywords.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldKeywords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldKeywordsActionPerformed(evt);
            }
        });

        jTextFieldContact.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldContactActionPerformed(evt);
            }
        });

        jTextFieldPage.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTextFieldCurationNote.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel57)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel58)
                .addGap(45, 45, 45)
                .addComponent(jLabel52))
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel31)
                    .addComponent(jLabel9)
                    .addComponent(jLabel32)
                    .addComponent(jLabel10)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel37)
                        .addComponent(jLabel12)
                        .addComponent(jLabel54)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldDOI, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldJournal, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldIssue, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldYear, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldVolume, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPage, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel38)
                    .addComponent(jLabel11)
                    .addComponent(jLabel45))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldAbstract, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldKeywords, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldContact, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(80, 80, 80)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel46)
                            .addComponent(jLabel15)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldPublishStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldCurationStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldCurationNote, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jLabel52))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldDOI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel31))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldJournal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel32))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldVolume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldIssue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel37))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel54)))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldPublishStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldCurationStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldCurationNote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel46)))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel38)
                                    .addComponent(jTextFieldKeywords, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldAbstract)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(jLabel45)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel57)
                    .addComponent(jLabel58)))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DOI", "Title", "Journal", "Year", "Volume", "Isue", "Page", "Contact author", "Keywords", "Abstract", "Publish status", "Cruration status", "Curation note"
            }
        )
        //make the jtable cell not editable
        {public boolean isCellEditable(int row, int column){return false;}}
    );
    jTable1.setGridColor(new java.awt.Color(204, 255, 0));

    jTable1.setSelectionBackground(new java.awt.Color(0, 153, 0));

    jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jTable1MouseClicked(evt);
        }
    });
    jScrollPane1.setViewportView(jTable1);

    jButtonAddPublication.setBackground(new java.awt.Color(204, 204, 204));
    jButtonAddPublication.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
    jButtonAddPublication.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaNanoSerenade/image/save_button.png"))); // NOI18N
    jButtonAddPublication.setBorderPainted(false);
    jButtonAddPublication.setContentAreaFilled(false);
    jButtonAddPublication.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jButtonAddPublication.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonAddPublicationActionPerformed(evt);
        }
    });

    jButtonRemovePublication.setBackground(new java.awt.Color(204, 204, 204));
    jButtonRemovePublication.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
    jButtonRemovePublication.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaNanoSerenade/image/remove_button.png"))); // NOI18N
    jButtonRemovePublication.setBorderPainted(false);
    jButtonRemovePublication.setContentAreaFilled(false);
    jButtonRemovePublication.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jButtonRemovePublication.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonRemovePublicationActionPerformed(evt);
        }
    });

    jButtonEditPublication.setBackground(new java.awt.Color(204, 204, 204));
    jButtonEditPublication.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
    jButtonEditPublication.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaNanoSerenade/image/edit_button.png"))); // NOI18N
    jButtonEditPublication.setBorderPainted(false);
    jButtonEditPublication.setContentAreaFilled(false);
    jButtonEditPublication.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jButtonEditPublication.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonEditPublicationActionPerformed(evt);
        }
    });

    jButtonClearPublication.setBackground(new java.awt.Color(204, 204, 204));
    jButtonClearPublication.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
    jButtonClearPublication.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaNanoSerenade/image/reset_button.png"))); // NOI18N
    jButtonClearPublication.setBorderPainted(false);
    jButtonClearPublication.setContentAreaFilled(false);
    jButtonClearPublication.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jButtonClearPublication.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonClearPublicationActionPerformed(evt);
        }
    });

    jButtonRefreshPublication.setBackground(new java.awt.Color(204, 204, 204));
    jButtonRefreshPublication.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
    jButtonRefreshPublication.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaNanoSerenade/image/refresh_button.png"))); // NOI18N
    jButtonRefreshPublication.setBorderPainted(false);
    jButtonRefreshPublication.setContentAreaFilled(false);
    jButtonRefreshPublication.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jButtonRefreshPublication.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonRefreshPublicationActionPerformed(evt);
        }
    });

    jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaNanoSerenade/image/exit_button.png"))); // NOI18N
    jButton1.setBorderPainted(false);
    jButton1.setContentAreaFilled(false);
    jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jButton1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton1ActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(37, 37, 37)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1204, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(51, 51, 51)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jButtonAddPublication, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(63, 63, 63)
                            .addComponent(jButtonEditPublication, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(72, 72, 72)
                            .addComponent(jButtonRemovePublication, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(67, 67, 67)
                            .addComponent(jButtonClearPublication, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(74, 74, 74)
                            .addComponent(jButtonRefreshPublication, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(79, 79, 79)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addContainerGap(68, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(7, 7, 7)
            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonRefreshPublication)
                    .addComponent(jButtonClearPublication)
                    .addComponent(jButtonAddPublication, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonEditPublication)
                    .addComponent(jButtonRemovePublication))
                .addComponent(jButton1))
            .addGap(13, 13, 13)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jMenu1.setText("File");
    jMenuBar1.add(jMenu1);

    jMenu2.setText("Edit");
    jMenuBar1.add(jMenu2);

    jMenu3.setText("Help");

    jMenu5.setText("Tutorial");
    jMenu3.add(jMenu5);
    jMenu3.add(jSeparator1);

    jMenu4.setText("About the SERENADE");
    jMenu3.add(jMenu4);

    jMenuBar1.add(jMenu3);

    setJMenuBar(jMenuBar1);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldDOIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDOIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDOIActionPerformed

    private void jTextFieldContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldContactActionPerformed

    private void jTextFieldKeywordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldKeywordsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldKeywordsActionPerformed

    private void jTextFieldAbstractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAbstractActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAbstractActionPerformed

    private void jButtonAddPublicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddPublicationActionPerformed
        //get data from jtextfields
       
            String doi = jTextFieldDOI.getText();
            String title = jTextFieldTitle.getText();        
            String journal = jTextFieldJournal.getText();
            String year = jTextFieldYear.getText();
            String volume = jTextFieldVolume.getText();
            String issue = jTextFieldIssue.getText();
            String page = jTextFieldPage.getText();
            String contact_author = jTextFieldContact.getText();        
            String keywords = jTextFieldKeywords.getText();
            String pabstract = jTextFieldAbstract.getText();
            String publish_status = jTextFieldPublishStatus.getText();
            String curation_status = jTextFieldCurationStatus.getText();
            String curation_note = jTextFieldCurationNote.getText();
            
            if(doi.trim().equals("") || title.trim().equals("") || journal.trim().equals("") || year.trim().equals("") || volume.trim().equals("") || issue.trim().equals("") || page.trim().equals("")|| contact_author.trim().equals("") || keywords.trim().equals("") || pabstract.trim().equals("")|| publish_status.trim().equals("") || curation_status.trim().equals("") || curation_note.trim().equals(""))
        {
            JOptionPane.showMessageDialog(rootPane, "Required Fields -> DOI + Title + Journal + Year + Vomume + and so on.", "Empty Fields", JOptionPane.WARNING_MESSAGE);
        }
        else {
            if(publication.addPublication(doi, title, journal, year, volume, issue, page, contact_author, keywords, pabstract, publish_status, curation_status, curation_note))
            {
                JOptionPane.showMessageDialog(rootPane, "New Publication added Successfully", "Add Publication", JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(rootPane, "Publication Not Added ", "Add Publication Error", JOptionPane.ERROR_MESSAGE);
            }
        }
            //clear the JTable first
       jTable1.setModel(new DefaultTableModel(null, new Object[]{"DOI", "Title", "Journal", "Year", "Volume", "Isue", "Page", "Contact author", "Keywords", "Abstract", "Publish status", "Cruration status", "Curation note"}));
       
        // then populate the JTable
        publication.fillPublicationJTable(jTable1);
        
    }//GEN-LAST:event_jButtonAddPublicationActionPerformed
   
    
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {                                     
        //display the selected row data in the jtextfields
        
        //get the jlabel model 
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                
        // get the selected row index
        int rIndex = jTable1.getSelectedRow();
        
        //display data 
        jTextFieldDOI.setText(model.getValueAt(rIndex, 0).toString());
        jTextFieldTitle.setText(model.getValueAt(rIndex, 1).toString());
        jTextFieldJournal.setText(model.getValueAt(rIndex, 2).toString());
        jTextFieldYear.setText(model.getValueAt(rIndex, 3).toString());
        jTextFieldVolume.setText(model.getValueAt(rIndex, 4).toString());
        jTextFieldIssue.setText(model.getValueAt(rIndex, 5).toString());
        jTextFieldPage.setText(model.getValueAt(rIndex, 6).toString());
        jTextFieldContact.setText(model.getValueAt(rIndex, 7).toString());
        jTextFieldKeywords.setText(model.getValueAt(rIndex, 8).toString());
        jTextFieldAbstract.setText(model.getValueAt(rIndex, 9).toString());
        jTextFieldPublishStatus.setText(model.getValueAt(rIndex, 10).toString());
        jTextFieldCurationStatus.setText(model.getValueAt(rIndex, 11).toString());
        jTextFieldCurationNote.setText(model.getValueAt(rIndex, 12).toString());
    }                             
    
    private void jButtonClearPublicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearPublicationActionPerformed
        // remove text from all jTextfields
        jTextFieldAbstract.setText("");
        jTextFieldContact.setText("");
        jTextFieldCurationNote.setText("");
        jTextFieldCurationStatus.setText("");
        jTextFieldDOI.setText("");
        jTextFieldIssue.setText("");
        jTextFieldJournal.setText("");
        jTextFieldKeywords.setText("");
        jTextFieldPage.setText("");
        jTextFieldPublishStatus.setText("");
        jTextFieldTitle.setText("");
        jTextFieldVolume.setText("");
        jTextFieldYear.setText("");
    }//GEN-LAST:event_jButtonClearPublicationActionPerformed

    private void jButtonRefreshPublicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefreshPublicationActionPerformed
         //clear the JTable first
       jTable1.setModel(new DefaultTableModel(null, new Object[]{"DOI", "Title", "Journal", "Year", "Volume", "Isue", "Page", "Contact author", "Keywords", "Abstract", "Publish status", "Cruration status", "Curation note"}));
       
        // then populate the JTable
        publication.fillPublicationJTable(jTable1);
    }//GEN-LAST:event_jButtonRefreshPublicationActionPerformed

    private void jButtonEditPublicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditPublicationActionPerformed
        // EDIT THE SELECTED CLIENT
        
        //get data from the fields
    try{
            String doi = jTextFieldDOI.getText();
            String title = jTextFieldTitle.getText();        
            String journal = jTextFieldJournal.getText();
            String year = jTextFieldYear.getText();
            String volume = jTextFieldVolume.getText();
            String issue = jTextFieldIssue.getText();
            String page = jTextFieldPage.getText();
            String contact_author = jTextFieldContact.getText();        
            String keywords = jTextFieldKeywords.getText();
            String pabstract = jTextFieldAbstract.getText();
            String publish_status = jTextFieldPublishStatus.getText();
            String curation_status = jTextFieldCurationStatus.getText();
            String curation_note = jTextFieldCurationNote.getText();
        
          
                      
         if(publication.editPublication(doi, title, journal, year, volume, issue, page, contact_author, keywords, pabstract, publish_status, curation_status, curation_note))
            {
                JOptionPane.showMessageDialog(rootPane, "Publication Data Updated Successfully", "Edit Publication", JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(rootPane, "Publication Data Not Updated ", "Edit Publication Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch(NumberFormatException ex)
              {
                JOptionPane.showMessageDialog(rootPane, ex.getMessage() + "Enter The Publication ID", "Publication ID Error", JOptionPane.ERROR_MESSAGE);
            }
    //clear the JTable first
       jTable1.setModel(new DefaultTableModel(null, new Object[]{"DOI", "Title", "Journal", "Year", "Volume", "Isue", "Page", "Contact author", "Keywords", "Abstract", "Publish status", "Cruration status", "Curation note"}));
       
        // then populate the JTable
        publication.fillPublicationJTable(jTable1);
   
    }//GEN-LAST:event_jButtonEditPublicationActionPerformed

    private void jButtonRemovePublicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemovePublicationActionPerformed
        try{
                    String doi = jTextFieldDOI.getText();
                    
                    if(publication.removePublication(doi))
                        {
                            JOptionPane.showMessageDialog(rootPane, "Publication Deleted Successfully", "Remove Publication", JOptionPane.INFORMATION_MESSAGE);
                    }
                    else{
                            JOptionPane.showMessageDialog(rootPane, "Publication Not Deleted ", "Remove Publication Error", JOptionPane.ERROR_MESSAGE);
                        }
               }
              catch(NumberFormatException ex)
              {
                JOptionPane.showMessageDialog(rootPane, ex.getMessage() + "Enter The Publication Id ", "Publication ID Error", JOptionPane.ERROR_MESSAGE);
            }
        //clear the JTable first
       jTable1.setModel(new DefaultTableModel(null, new Object[]{"DOI", "Title", "Journal", "Year", "Volume", "Isue", "Page", "Contact author", "Keywords", "Abstract", "Publish status", "Cruration status", "Curation note"}));
       
        // then populate the JTable
        publication.fillPublicationJTable(jTable1);
    }//GEN-LAST:event_jButtonRemovePublicationActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagePublicationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagePublicationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagePublicationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagePublicationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagePublicationForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAddPublication;
    private javax.swing.JButton jButtonClearPublication;
    private javax.swing.JButton jButtonEditPublication;
    private javax.swing.JButton jButtonRefreshPublication;
    private javax.swing.JButton jButtonRemovePublication;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldAbstract;
    private javax.swing.JTextField jTextFieldContact;
    private javax.swing.JTextField jTextFieldCurationNote;
    private javax.swing.JTextField jTextFieldCurationStatus;
    private javax.swing.JTextField jTextFieldDOI;
    private javax.swing.JTextField jTextFieldIssue;
    private javax.swing.JTextField jTextFieldJournal;
    private javax.swing.JTextField jTextFieldKeywords;
    private javax.swing.JTextField jTextFieldPage;
    private javax.swing.JTextField jTextFieldPublishStatus;
    private javax.swing.JTextField jTextFieldTitle;
    private javax.swing.JTextField jTextFieldVolume;
    private javax.swing.JTextField jTextFieldYear;
    // End of variables declaration//GEN-END:variables
}
