/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaNanoSerenade;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aliay
 */
public class ManageMeasurementForm extends javax.swing.JFrame {

    MEASUREMENT measurement = new MEASUREMENT();
    /**
     * Creates new form ManageRoomsForm
     */
    public ManageMeasurementForm() {
        initComponents();
        
         //ajout d une icone serende pour la page
          this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/javaNanoSerenade/image/lloogg_ser.png")).getImage());
          
          
         //populate the jtable
        measurement.fillMeasurementJTable(jTable1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jTextFieldMeasType = new javax.swing.JTextField();
        jTextFieldMeasID = new javax.swing.JTextField();
        jTextFieldDOI = new javax.swing.JTextField();
        jLabel52 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jTextFieldSourceID = new javax.swing.JTextField();
        jTextFieldReferencingID = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jTextFieldTimeRelative = new javax.swing.JTextField();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldSourceDOI = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jTextFieldparameterStatistics = new javax.swing.JTextField();
        jTextFieldparameterText = new javax.swing.JTextField();
        jTextFieldParameterDataType = new javax.swing.JTextField();
        jTextFieldParameterDescription = new javax.swing.JTextField();
        jTextFieldParameter = new javax.swing.JTextField();
        jTextFieldTimeAbsolute = new javax.swing.JTextField();
        jTextFieldTimeUnit = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextFieldinstrumentId = new javax.swing.JTextField();
        jTextFieldProtocolId = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jTextFieldOwnerGroup = new javax.swing.JTextField();
        jTextFieldparameterUncertaintyUpper = new javax.swing.JTextField();
        jTextFieldparameterUncertaintyUnit = new javax.swing.JTextField();
        jTextFieldparameterUncertaintyLow = new javax.swing.JTextField();
        jTextFieldparameterUncertaintyType = new javax.swing.JTextField();
        jTextFieldparameterUnit = new javax.swing.JTextField();
        jTextFieldparameterNumericOperator = new javax.swing.JTextField();
        jTextFieldparameterNumeric = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jTextFieldInherentID = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonAddMeasurement = new javax.swing.JButton();
        jButtonRemoveMeasurement = new javax.swing.JButton();
        jButtonEditMeasurement = new javax.swing.JButton();
        jButtonClearMeasurement = new javax.swing.JButton();
        jButtonRefreshMeasurement = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenu4 = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manage Measurement");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel10.setBackground(new java.awt.Color(204, 204, 204));
        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.MatteBorder(null), "Measurement informations", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 16))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel9.setText("DOI:");

        jLabel31.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel31.setText("Measurement ID:");

        jLabel32.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel32.setText("Measurement Type:");

        jTextFieldMeasType.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTextFieldMeasID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldMeasID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMeasIDActionPerformed(evt);
            }
        });

        jTextFieldDOI.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldDOI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDOIActionPerformed(evt);
            }
        });

        jLabel37.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel37.setText("Source ID:");

        jTextFieldSourceID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTextFieldReferencingID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel10.setText("Referencing ID:");

        jLabel54.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel54.setText("Time Relative:");

        jTextFieldTimeRelative.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel57.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel12.setText("Source DOI:");

        jTextFieldSourceDOI.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel11.setText("Time Unit:");

        jLabel33.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel33.setText("Time Absolute:");

        jLabel34.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel34.setText("Parameter:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel13.setText("Parameter Description:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel14.setText("Parameter DataType:");

        jLabel38.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel38.setText("Parameter Text:");

        jLabel60.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel60.setText("Parameter Statistics:");

        jTextFieldparameterStatistics.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTextFieldparameterText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTextFieldParameterDataType.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTextFieldParameterDescription.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTextFieldParameter.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTextFieldTimeAbsolute.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTextFieldTimeUnit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldTimeUnit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTimeUnitActionPerformed(evt);
            }
        });

        jLabel35.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel35.setText("Instrument ID:");

        jLabel17.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel17.setText("Owner Group:");

        jTextFieldinstrumentId.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTextFieldProtocolId.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel36.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel36.setText("Protocol ID:");

        jTextFieldOwnerGroup.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldOwnerGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldOwnerGroupActionPerformed(evt);
            }
        });

        jTextFieldparameterUncertaintyUpper.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTextFieldparameterUncertaintyUnit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTextFieldparameterUncertaintyLow.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTextFieldparameterUncertaintyType.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTextFieldparameterUnit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTextFieldparameterNumericOperator.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTextFieldparameterNumeric.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldparameterNumeric.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldparameterNumericActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel18.setText("Parameter Numeric:");

        jLabel40.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel40.setText("Parameter Numeric Operator:");

        jLabel41.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel41.setText("Parameter Unit:");

        jLabel19.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel19.setText("Parameter Uncertainty Type:");

        jLabel20.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel20.setText("Parameter Uncertainty Lower:");

        jLabel42.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel42.setText("Parameter Uncertainty Unit:");

        jLabel62.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel62.setText("Parameter Uncertainty Upper:");

        jTextFieldInherentID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel39.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel39.setText("Inherent ID:");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel32)
                        .addGap(3, 3, 3)
                        .addComponent(jTextFieldMeasType, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel13)
                        .addGap(52, 52, 52)
                        .addComponent(jTextFieldParameterDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(jLabel42)
                        .addGap(37, 37, 37)
                        .addComponent(jTextFieldparameterUncertaintyUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldReferencingID, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldSourceDOI, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGap(120, 120, 120)
                                .addComponent(jLabel57))
                            .addComponent(jLabel38))
                        .addGap(63, 63, 63)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldParameterDataType, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldparameterText, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel62)
                            .addComponent(jLabel17))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldparameterUncertaintyUpper, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(jLabel58))
                            .addComponent(jTextFieldOwnerGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel37)
                        .addGap(66, 66, 66)
                        .addComponent(jTextFieldSourceID, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel60)
                        .addGap(67, 67, 67)
                        .addComponent(jTextFieldparameterStatistics, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(jLabel36)
                        .addGap(146, 146, 146)
                        .addComponent(jTextFieldProtocolId, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel54)
                        .addGap(44, 44, 44)
                        .addComponent(jTextFieldTimeRelative, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel18)
                        .addGap(72, 72, 72)
                        .addComponent(jTextFieldparameterNumericOperator, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(jLabel35)
                        .addGap(124, 124, 124)
                        .addComponent(jTextFieldinstrumentId, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(70, 70, 70)
                        .addComponent(jTextFieldTimeUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel40)
                        .addGap(5, 5, 5)
                        .addComponent(jTextFieldparameterNumeric, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel33)
                        .addGap(37, 37, 37)
                        .addComponent(jTextFieldTimeAbsolute, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel41)
                        .addGap(101, 101, 101)
                        .addComponent(jTextFieldparameterUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(jLabel31)
                                .addGap(20, 20, 20)
                                .addComponent(jTextFieldMeasID, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(107, 107, 107)
                                .addComponent(jTextFieldDOI, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(jLabel34)
                                .addGap(134, 134, 134)
                                .addComponent(jTextFieldParameter, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55)
                                .addComponent(jLabel19)
                                .addGap(31, 31, 31)
                                .addComponent(jTextFieldparameterUncertaintyType, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(jLabel39)
                                .addGap(123, 123, 123)
                                .addComponent(jTextFieldInherentID, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59)
                                .addComponent(jLabel20)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldparameterUncertaintyLow, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel9))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jTextFieldDOI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldParameter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel34))
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldparameterUncertaintyType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel31))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jTextFieldMeasID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel39))
                    .addComponent(jTextFieldInherentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldparameterUncertaintyLow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel20)))
                .addGap(2, 2, 2)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel32))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jTextFieldMeasType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldParameterDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldparameterUncertaintyUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel42)))
                .addGap(2, 2, 2)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jTextFieldParameterDataType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldparameterText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldparameterUncertaintyUpper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel62))
                        .addGap(9, 9, 9)
                        .addComponent(jLabel58)
                        .addGap(3, 3, 3)
                        .addComponent(jTextFieldOwnerGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)
                                .addComponent(jLabel12))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(jTextFieldReferencingID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jTextFieldSourceDOI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(10, 10, 10)
                                .addComponent(jLabel57)
                                .addGap(13, 13, 13)
                                .addComponent(jLabel38)))))
                .addGap(2, 2, 2)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel37))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jTextFieldSourceID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel60))
                    .addComponent(jTextFieldparameterStatistics, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel36))
                    .addComponent(jTextFieldProtocolId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel54))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jTextFieldTimeRelative, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel18))
                    .addComponent(jTextFieldparameterNumericOperator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel35))
                    .addComponent(jTextFieldinstrumentId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel11))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jTextFieldTimeUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel40))
                    .addComponent(jTextFieldparameterNumeric, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel33))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jTextFieldTimeAbsolute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel41))
                    .addComponent(jTextFieldparameterUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DOI", "Measurement ID", "Measurement type", "Referencing ID", "Source DOI", "Source ID", "Time relative", "Time unit", "Time absolute", "Parameter", "Inherit ID", "Parameter description", "Parameter datatype", "Parameter text", "Parameter statistic", "Parameter numeric", "Parameter numeric operator", "Parameter unit", "Parameter uncertainty type", "Parameter uncertainty lower", "Parameter uncertainty upper", "Parameter uncertainty unit", "Owner group", "Protocol ID", "Instrument ID"
            }
        )
        //make the jtable cell not editable
        {public boolean isCellEditable(int row, int column){return false;}}
    );
    jTable1.setGridColor(new java.awt.Color(204, 255, 0));

    jTable1.setSelectionBackground(new java.awt.Color(0, 153, 0));

    jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jTable1MouseClicked(evt);
        }
    });
    jScrollPane1.setViewportView(jTable1);

    jButtonAddMeasurement.setBackground(new java.awt.Color(204, 204, 204));
    jButtonAddMeasurement.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
    jButtonAddMeasurement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaNanoSerenade/image/save_button.png"))); // NOI18N
    jButtonAddMeasurement.setBorderPainted(false);
    jButtonAddMeasurement.setContentAreaFilled(false);
    jButtonAddMeasurement.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jButtonAddMeasurement.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonAddMeasurementActionPerformed(evt);
        }
    });

    jButtonRemoveMeasurement.setBackground(new java.awt.Color(204, 204, 204));
    jButtonRemoveMeasurement.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
    jButtonRemoveMeasurement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaNanoSerenade/image/remove_button.png"))); // NOI18N
    jButtonRemoveMeasurement.setBorderPainted(false);
    jButtonRemoveMeasurement.setContentAreaFilled(false);
    jButtonRemoveMeasurement.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jButtonRemoveMeasurement.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonRemoveMeasurementActionPerformed(evt);
        }
    });

    jButtonEditMeasurement.setBackground(new java.awt.Color(204, 204, 204));
    jButtonEditMeasurement.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
    jButtonEditMeasurement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaNanoSerenade/image/edit_button.png"))); // NOI18N
    jButtonEditMeasurement.setBorderPainted(false);
    jButtonEditMeasurement.setContentAreaFilled(false);
    jButtonEditMeasurement.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jButtonEditMeasurement.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonEditMeasurementActionPerformed(evt);
        }
    });

    jButtonClearMeasurement.setBackground(new java.awt.Color(204, 204, 204));
    jButtonClearMeasurement.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
    jButtonClearMeasurement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaNanoSerenade/image/reset_button.png"))); // NOI18N
    jButtonClearMeasurement.setBorderPainted(false);
    jButtonClearMeasurement.setContentAreaFilled(false);
    jButtonClearMeasurement.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jButtonClearMeasurement.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonClearMeasurementActionPerformed(evt);
        }
    });

    jButtonRefreshMeasurement.setBackground(new java.awt.Color(204, 204, 204));
    jButtonRefreshMeasurement.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
    jButtonRefreshMeasurement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaNanoSerenade/image/refresh_button.png"))); // NOI18N
    jButtonRefreshMeasurement.setBorderPainted(false);
    jButtonRefreshMeasurement.setContentAreaFilled(false);
    jButtonRefreshMeasurement.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jButtonRefreshMeasurement.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonRefreshMeasurementActionPerformed(evt);
        }
    });

    jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaNanoSerenade/image/exit_button.png"))); // NOI18N
    jButton1.setBorderPainted(false);
    jButton1.setContentAreaFilled(false);
    jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jButton1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton1ActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(87, 87, 87)
                    .addComponent(jButtonAddMeasurement, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(68, 68, 68)
                    .addComponent(jButtonEditMeasurement, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(67, 67, 67)
                    .addComponent(jButtonRemoveMeasurement, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(71, 71, 71)
                    .addComponent(jButtonClearMeasurement, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(70, 70, 70)
                    .addComponent(jButtonRefreshMeasurement, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(65, 65, 65)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1262, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap(24, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jButtonRefreshMeasurement)
                .addComponent(jButtonClearMeasurement)
                .addComponent(jButtonRemoveMeasurement)
                .addComponent(jButtonEditMeasurement)
                .addComponent(jButtonAddMeasurement)
                .addComponent(jButton1))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(123, Short.MAX_VALUE))
    );

    jMenu1.setText("File");
    jMenuBar1.add(jMenu1);

    jMenu2.setText("Edit");
    jMenuBar1.add(jMenu2);

    jMenu3.setText("Help");

    jMenu5.setText("Tutorial");
    jMenu3.add(jMenu5);
    jMenu3.add(jSeparator1);

    jMenu4.setText("About the SERENADE");
    jMenu3.add(jMenu4);

    jMenuBar1.add(jMenu3);

    setJMenuBar(jMenuBar1);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldDOIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDOIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDOIActionPerformed

    private void jTextFieldTimeUnitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTimeUnitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTimeUnitActionPerformed

    private void jTextFieldOwnerGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldOwnerGroupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldOwnerGroupActionPerformed

    private void jTextFieldparameterNumericActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldparameterNumericActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldparameterNumericActionPerformed

    private void jButtonAddMeasurementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddMeasurementActionPerformed
         //get data from jtextfields
       try{
            String doi = jTextFieldDOI.getText();
            int measurementID = Integer.parseInt(jTextFieldMeasID.getText());
            String measurementType = jTextFieldMeasType.getText();
            int referencingID = Integer.parseInt(jTextFieldReferencingID.getText());
            String sourceDOI = jTextFieldSourceDOI.getText();
            int sourceID = Integer.parseInt(jTextFieldSourceID.getText());
            float timeRelative = Integer.parseInt(jTextFieldTimeRelative.getText());
            String timeUnit = jTextFieldTimeUnit.getText();
            float timeAbsolute = Float.parseFloat(jTextFieldTimeAbsolute.getText());
            String parameter = jTextFieldParameter.getText();
            int inheritID = Integer.parseInt(jTextFieldInherentID.getText());
            String parameterDescription = jTextFieldParameterDescription.getText();
            String parameterDataType = jTextFieldParameterDataType.getText();
            String parameterText = jTextFieldparameterText.getText();
            String parameterStatistic = jTextFieldparameterStatistics.getText();
            float parameterNumeric = Float.parseFloat(jTextFieldparameterNumeric.getText());
            String parameterNumericOperator = jTextFieldparameterNumericOperator.getText();
            int parameterUnit = Integer.parseInt(jTextFieldparameterUnit.getText());
            String parameterUncertaintyType = jTextFieldparameterUncertaintyType.getText();
            float parameterUncertaintyLower = Float.parseFloat(jTextFieldparameterUncertaintyLow.getText());
            float parameterUncertaintyUpper = Float.parseFloat(jTextFieldparameterUncertaintyUpper.getText());
            String parameterUncertaintyUnit = jTextFieldparameterUncertaintyUnit.getText();
            int ownerGroup = Integer.parseInt(jTextFieldOwnerGroup.getText());
            int protocolID = Integer.parseInt(jTextFieldProtocolId.getText());
            int instrumentID = Integer.parseInt(jTextFieldinstrumentId.getText());
        
            if(measurement.addMeasurement(doi, measurementID, measurementType, referencingID, sourceDOI, sourceID, timeRelative, timeUnit, timeAbsolute, parameter, inheritID, parameterDescription, parameterDataType, parameterText, parameterStatistic, parameterNumeric, parameterNumericOperator, parameterUnit, parameterUncertaintyType, parameterUncertaintyLower, parameterUncertaintyUpper, parameterUncertaintyUnit, ownerGroup, protocolID, instrumentID))
            {
                JOptionPane.showMessageDialog(rootPane, "New Measurement added Successfully", "Add Measurement", JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(rootPane, "Measurement Not Added ", "Add Measurement Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch(NumberFormatException ex)
              {
                JOptionPane.showMessageDialog(rootPane, ex.getMessage() + "Enter The Measurement ID", "Measurement ID Error", JOptionPane.ERROR_MESSAGE);
            }
       //clear the JTable first
       jTable1.setModel(new DefaultTableModel(null, new Object[]{"DOI", "Measurement ID", "Measurement type", "Referencing ID", "Source DOI", "Source ID", "Time relative", "Time unit", "Time absolute", "Parameter", "Inherit ID", "Parameter description", "Parameter datatype", "Parameter text", "Parameter statistic", "Parameter numeric", "Parameter numeric operator", "Parameter unit", "Parameter uncertainty type", "Parameter uncertainty lower", "Parameter uncertainty upper", "Parameter uncertainty unit", "Owner group", "Protocol ID", "Instrument ID"}));
       
        // then populate the JTable
        measurement.fillMeasurementJTable(jTable1);
    }//GEN-LAST:event_jButtonAddMeasurementActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {                                     
        //display the selected row data in the jtextfields
        
        //get the jlabel model 
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                
        // get the selected row index
        int rIndex = jTable1.getSelectedRow();
        
        //display data 
        jTextFieldDOI.setText(model.getValueAt(rIndex, 0).toString());
        jTextFieldMeasID.setText(model.getValueAt(rIndex, 1).toString());
        jTextFieldMeasType.setText(model.getValueAt(rIndex, 2).toString());
        //String injectionMode = jComboBoxInjection.getSelectedItem().toString();
        //String ecosystem = jComboBoxEcosystem.getSelectedItem().toString();
        jTextFieldReferencingID.setText(model.getValueAt(rIndex, 3).toString());
        jTextFieldSourceDOI.setText(model.getValueAt(rIndex, 4).toString());
        jTextFieldSourceID.setText(model.getValueAt(rIndex, 5).toString());
        jTextFieldTimeRelative.setText(model.getValueAt(rIndex, 6).toString());
        jTextFieldTimeUnit.setText(model.getValueAt(rIndex, 7).toString());
        jTextFieldTimeAbsolute.setText(model.getValueAt(rIndex, 8).toString());
        jTextFieldParameter.setText(model.getValueAt(rIndex, 9).toString());
        jTextFieldInherentID.setText(model.getValueAt(rIndex, 10).toString());
        jTextFieldParameterDescription.setText(model.getValueAt(rIndex, 11).toString());
        jTextFieldParameterDataType.setText(model.getValueAt(rIndex, 12).toString());
        jTextFieldparameterText.setText(model.getValueAt(rIndex, 13).toString());
        jTextFieldparameterStatistics.setText(model.getValueAt(rIndex, 14).toString());
        jTextFieldparameterNumeric.setText(model.getValueAt(rIndex, 15).toString());
        jTextFieldparameterNumericOperator.setText(model.getValueAt(rIndex, 16).toString());
        jTextFieldparameterUnit.setText(model.getValueAt(rIndex, 17).toString());
        jTextFieldparameterUncertaintyType.setText(model.getValueAt(rIndex, 19).toString());
        jTextFieldparameterUncertaintyLow.setText(model.getValueAt(rIndex, 20).toString());
        jTextFieldparameterUncertaintyUpper.setText(model.getValueAt(rIndex, 21).toString());
        jTextFieldparameterUncertaintyUnit.setText(model.getValueAt(rIndex, 22).toString());
        jTextFieldOwnerGroup.setText(model.getValueAt(rIndex, 23).toString());
        jTextFieldProtocolId.setText(model.getValueAt(rIndex, 24).toString());
        jTextFieldinstrumentId.setText(model.getValueAt(rIndex, 25).toString());
        
               
    }
    
    private void jButtonClearMeasurementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearMeasurementActionPerformed
        // remove text from all jTextfields
        jTextFieldMeasID.setText("");
        jTextFieldMeasType.setText("");
        jTextFieldOwnerGroup.setText("");
        jTextFieldParameter.setText("");
        jTextFieldDOI.setText("");
        jTextFieldParameterDataType.setText("");
        jTextFieldParameterDescription.setText("");
        jTextFieldProtocolId.setText("");
        jTextFieldReferencingID.setText("");
        jTextFieldSourceDOI.setText("");
        jTextFieldSourceID.setText("");
        jTextFieldTimeAbsolute.setText("");
        jTextFieldTimeRelative.setText("");
        jTextFieldTimeUnit.setText("");
        jTextFieldinstrumentId.setText("");
        jTextFieldparameterNumeric.setText("");
        jTextFieldparameterNumericOperator.setText("");
        jTextFieldparameterStatistics.setText("");
        jTextFieldparameterText.setText("");
        jTextFieldparameterUncertaintyLow.setText("");
        jTextFieldparameterUncertaintyType.setText("");
        jTextFieldparameterUncertaintyUnit.setText("");
        jTextFieldparameterUncertaintyUpper.setText("");
        jTextFieldparameterUnit.setText("");
        
    }//GEN-LAST:event_jButtonClearMeasurementActionPerformed

    private void jButtonRefreshMeasurementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefreshMeasurementActionPerformed
         //clear the JTable first
       jTable1.setModel(new DefaultTableModel(null, new Object[]{"DOI", "Measurement ID", "Measurement type", "Referencing ID", "Source DOI", "Source ID", "Time relative", "Time unit", "Time absolute", "Parameter", "Inherit ID", "Parameter description", "Parameter datatype", "Parameter text", "Parameter statistic", "Parameter numeric", "Parameter numeric operator", "Parameter unit", "Parameter uncertainty type", "Parameter uncertainty lower", "Parameter uncertainty upper", "Parameter uncertainty unit", "Owner group", "Protocol ID", "Instrument ID"}));
       
        // then populate the JTable
        measurement.fillMeasurementJTable(jTable1);
    }//GEN-LAST:event_jButtonRefreshMeasurementActionPerformed

    private void jButtonRemoveMeasurementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveMeasurementActionPerformed
        try{
                    String doi = jTextFieldDOI.getText();
                    
                    if(measurement.removeMeasurement(doi))
                        {
                            JOptionPane.showMessageDialog(rootPane, "Measurement Deleted Successfully", "Remove Measurement", JOptionPane.INFORMATION_MESSAGE);
                    }
                    else{
                            JOptionPane.showMessageDialog(rootPane, "Measurement Not Deleted ", "Remove Measurement Error", JOptionPane.ERROR_MESSAGE);
                        }
               }
              catch(NumberFormatException ex)
              {
                JOptionPane.showMessageDialog(rootPane, ex.getMessage() + "Enter The Measurement Id ", "Measurement ID Error", JOptionPane.ERROR_MESSAGE);
            }
        //clear the JTable first
       jTable1.setModel(new DefaultTableModel(null, new Object[]{"DOI", "Measurement ID", "Measurement type", "Referencing ID", "Source DOI", "Source ID", "Time relative", "Time unit", "Time absolute", "Parameter", "Inherit ID", "Parameter description", "Parameter datatype", "Parameter text", "Parameter statistic", "Parameter numeric", "Parameter numeric operator", "Parameter unit", "Parameter uncertainty type", "Parameter uncertainty lower", "Parameter uncertainty upper", "Parameter uncertainty unit", "Owner group", "Protocol ID", "Instrument ID"}));
       
        // then populate the JTable
        measurement.fillMeasurementJTable(jTable1);
    }//GEN-LAST:event_jButtonRemoveMeasurementActionPerformed

    private void jButtonEditMeasurementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditMeasurementActionPerformed
        // EDIT THE SELECTED CLIENT
        
        //get data from the fields
    try{
            String doi = jTextFieldDOI.getText();
            int measurementID = Integer.parseInt(jTextFieldMeasID.getText());
            String measurementType = jTextFieldMeasType.getText();
            int referencingID = Integer.parseInt(jTextFieldReferencingID.getText());
            String sourceDOI = jTextFieldSourceDOI.getText();
            int sourceID = Integer.parseInt(jTextFieldSourceID.getText());
            float timeRelative = Integer.parseInt(jTextFieldTimeRelative.getText());
            String timeUnit = jTextFieldTimeUnit.getText();
            float timeAbsolute = Float.parseFloat(jTextFieldTimeAbsolute.getText());
            String parameter = jTextFieldParameter.getText();
            int inheritID = Integer.parseInt(jTextFieldInherentID.getText());
            String parameterDescription = jTextFieldParameterDescription.getText();
            String parameterDataType = jTextFieldParameterDataType.getText();
            String parameterText = jTextFieldparameterText.getText();
            String parameterStatistic = jTextFieldparameterStatistics.getText();
            float parameterNumeric = Float.parseFloat(jTextFieldparameterNumeric.getText());
            String parameterNumericOperator = jTextFieldparameterNumericOperator.getText();
            int parameterUnit = Integer.parseInt(jTextFieldparameterUnit.getText());
            String parameterUncertaintyType = jTextFieldparameterUncertaintyType.getText();
            float parameterUncertaintyLower = Float.parseFloat(jTextFieldparameterUncertaintyLow.getText());
            float parameterUncertaintyUpper = Float.parseFloat(jTextFieldparameterUncertaintyUpper.getText());
            String parameterUncertaintyUnit = jTextFieldparameterUncertaintyUnit.getText();
            int ownerGroup = Integer.parseInt(jTextFieldOwnerGroup.getText());
            int protocolID = Integer.parseInt(jTextFieldProtocolId.getText());
            int instrumentID = Integer.parseInt(jTextFieldinstrumentId.getText());
        
          
                      
         if(measurement.editMeasurement(doi, measurementID, measurementType, referencingID, sourceDOI, sourceID, timeRelative, timeUnit, timeAbsolute, parameter, inheritID, parameterDescription, parameterDataType, parameterText, parameterStatistic, parameterNumeric, parameterNumericOperator, parameterUnit, parameterUncertaintyType, parameterUncertaintyLower, parameterUncertaintyUpper, parameterUncertaintyUnit, ownerGroup, protocolID, instrumentID))
            {
                JOptionPane.showMessageDialog(rootPane, "Measurement Data Updated Successfully", "Edit Measurement", JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(rootPane, "Measurement Data Not Updated ", "Edit Measurement Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch(NumberFormatException ex)
              {
                JOptionPane.showMessageDialog(rootPane, ex.getMessage() + "Enter The Measurement ID", "Measurement ID Error", JOptionPane.ERROR_MESSAGE);
            }
    //clear the JTable first
       jTable1.setModel(new DefaultTableModel(null, new Object[]{"DOI", "Measurement ID", "Measurement type", "Referencing ID", "Source DOI", "Source ID", "Time relative", "Time unit", "Time absolute", "Parameter", "Inherit ID", "Parameter description", "Parameter datatype", "Parameter text", "Parameter statistic", "Parameter numeric", "Parameter numeric operator", "Parameter unit", "Parameter uncertainty type", "Parameter uncertainty lower", "Parameter uncertainty upper", "Parameter uncertainty unit", "Owner group", "Protocol ID", "Instrument ID"}));
       
        // then populate the JTable
        measurement.fillMeasurementJTable(jTable1);
    }//GEN-LAST:event_jButtonEditMeasurementActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextFieldMeasIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMeasIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMeasIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageMeasurementForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageMeasurementForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageMeasurementForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageMeasurementForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageMeasurementForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAddMeasurement;
    private javax.swing.JButton jButtonClearMeasurement;
    private javax.swing.JButton jButtonEditMeasurement;
    private javax.swing.JButton jButtonRefreshMeasurement;
    private javax.swing.JButton jButtonRemoveMeasurement;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldDOI;
    private javax.swing.JTextField jTextFieldInherentID;
    private javax.swing.JTextField jTextFieldMeasID;
    private javax.swing.JTextField jTextFieldMeasType;
    private javax.swing.JTextField jTextFieldOwnerGroup;
    private javax.swing.JTextField jTextFieldParameter;
    private javax.swing.JTextField jTextFieldParameterDataType;
    private javax.swing.JTextField jTextFieldParameterDescription;
    private javax.swing.JTextField jTextFieldProtocolId;
    private javax.swing.JTextField jTextFieldReferencingID;
    private javax.swing.JTextField jTextFieldSourceDOI;
    private javax.swing.JTextField jTextFieldSourceID;
    private javax.swing.JTextField jTextFieldTimeAbsolute;
    private javax.swing.JTextField jTextFieldTimeRelative;
    private javax.swing.JTextField jTextFieldTimeUnit;
    private javax.swing.JTextField jTextFieldinstrumentId;
    private javax.swing.JTextField jTextFieldparameterNumeric;
    private javax.swing.JTextField jTextFieldparameterNumericOperator;
    private javax.swing.JTextField jTextFieldparameterStatistics;
    private javax.swing.JTextField jTextFieldparameterText;
    private javax.swing.JTextField jTextFieldparameterUncertaintyLow;
    private javax.swing.JTextField jTextFieldparameterUncertaintyType;
    private javax.swing.JTextField jTextFieldparameterUncertaintyUnit;
    private javax.swing.JTextField jTextFieldparameterUncertaintyUpper;
    private javax.swing.JTextField jTextFieldparameterUnit;
    // End of variables declaration//GEN-END:variables
}
