/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaNanoSerenade;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author aliay
 */
public class ManageMesocosmsForm extends javax.swing.JFrame {
        
    MESOCOSM mesocosm = new MESOCOSM();
    /**
     * Creates new form ManageRoomsForm
     */
    public ManageMesocosmsForm() {
        initComponents();
        
         //ajout d une icone serende pour la page
          this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/javaNanoSerenade/image/lloogg_ser.png")).getImage());
        
        //populate the jtable
        mesocosm.fillMesocosmJTable(jTable1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jTextFieldAlgae = new javax.swing.JTextField();
        jTextFieldTAOC = new javax.swing.JTextField();
        jTextFieldTBARS = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jTextFieldBacteria = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldSedSpeciation = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldSedConcentration = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jTextFieldWatSpeciation = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jTextFieldDissConcentration = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jTextFieldWatConcentration = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        jTextFieldSize = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jTextFieldConductivity = new javax.swing.JTextField();
        jTextFieldTemp = new javax.swing.JTextField();
        jTextFieldPH = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jTextFieldWatORP = new javax.swing.JTextField();
        jTextFieldDissOxygen = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jTextFieldSEDORP = new javax.swing.JTextField();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldDOC = new javax.swing.JTextField();
        jLabel59 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jTextFieldDOI = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jTextFieldTotDose = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jComboBoxInjection = new javax.swing.JComboBox<>();
        jLabel29 = new javax.swing.JLabel();
        jComboBoxEcosystem = new javax.swing.JComboBox<>();
        jTextFieldTotTime = new javax.swing.JTextField();
        jLabel76 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonAddMesocosm = new javax.swing.JButton();
        jButtonRemoveMesocosm = new javax.swing.JButton();
        jButtonEditMesocosm = new javax.swing.JButton();
        jButtonClearMesocosm = new javax.swing.JButton();
        jButtonRefreshMesocosm = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jTextFieldName = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jTextFieldMeasTime = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jButtonImport = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenu4 = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manage Mesocosms (SERENADE)");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.MatteBorder(null), "Hazard End Points", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 16))); // NOI18N

        jTextFieldAlgae.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTextFieldTAOC.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldTAOC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTAOCActionPerformed(evt);
            }
        });

        jTextFieldTBARS.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldTBARS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTBARSActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel21.setText("TBARS:");

        jLabel20.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel20.setText("TAOC:");

        jLabel19.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel19.setText("Algae:");

        jTextFieldBacteria.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel26.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel26.setText("Bacteria:");

        jLabel33.setText("planorbes");

        jLabel34.setText("planorbes");

        jLabel35.setText("Bact/m l x105");

        jLabel36.setText("cell/m l x105");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldBacteria, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addComponent(jTextFieldTAOC, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addComponent(jTextFieldAlgae, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addComponent(jTextFieldTBARS, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel33)
                    .addComponent(jLabel34)
                    .addComponent(jLabel35)
                    .addComponent(jLabel36))
                .addGap(15, 15, 15))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jTextFieldTBARS, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jTextFieldTAOC, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jTextFieldAlgae, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jTextFieldBacteria, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35))
                .addContainerGap(114, Short.MAX_VALUE))
        );

        jPanel9.setBackground(new java.awt.Color(204, 204, 204));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.MatteBorder(null), "Exposure End Points", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 16))); // NOI18N

        jPanel7.setBackground(new java.awt.Color(204, 204, 204));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Sediment", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel6.setText("Speciation:");

        jTextFieldSedSpeciation.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel40.setText("ppb");

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel7.setText("Concentration:");

        jTextFieldSedConcentration.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel39.setText("ppm");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextFieldSedConcentration, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldSedSpeciation, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel40)
                    .addComponent(jLabel39))
                .addGap(39, 39, 39))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldSedSpeciation, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel40))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldSedConcentration, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel39))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel11.setBackground(new java.awt.Color(204, 204, 204));
        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Water", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jLabel22.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel22.setText("Speciation:");

        jTextFieldWatSpeciation.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldWatSpeciation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldWatSpeciationActionPerformed(evt);
            }
        });

        jLabel41.setText("ppb");

        jLabel23.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel23.setText("Dissolved Concentration:");

        jTextFieldDissConcentration.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel42.setText("ppb");

        jLabel24.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel24.setText("Concentration:");

        jTextFieldWatConcentration.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel43.setText("ppb");

        jTextFieldSize.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel28.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel28.setText("Size / Aggregation state:");

        jLabel44.setText("ppb");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(jLabel23)
                    .addComponent(jLabel22)
                    .addComponent(jLabel28))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jTextFieldSize, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel11Layout.createSequentialGroup()
                            .addComponent(jTextFieldWatSpeciation, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel42))
                        .addGroup(jPanel11Layout.createSequentialGroup()
                            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextFieldDissConcentration, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldWatConcentration, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel43)
                                .addComponent(jLabel41)))))
                .addGap(8, 8, 8))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jTextFieldWatSpeciation, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel42))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jTextFieldWatConcentration, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel43))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jTextFieldDissConcentration, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel41))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(jTextFieldSize, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel44))
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
        );

        jPanel10.setBackground(new java.awt.Color(204, 204, 204));
        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.MatteBorder(null), "Environmental End Points", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 16))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel9.setText("PH:");

        jLabel31.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel31.setText("Temperature:");

        jLabel32.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel32.setText("Conductivity:");

        jTextFieldConductivity.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTextFieldTemp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTextFieldPH.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldPH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPHActionPerformed(evt);
            }
        });

        jLabel50.setText("ppb");

        jLabel51.setText("°C");

        jLabel37.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel37.setText("Oxidation-Reduction Potential (wat.):");

        jLabel53.setText("mV");

        jTextFieldWatORP.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTextFieldDissOxygen.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel10.setText("Dissolved Oxygen:");

        jLabel54.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel54.setText("Oxidation-Reduction Potential (sed.):     ");

        jLabel55.setText("mV");

        jLabel56.setText("%");

        jTextFieldSEDORP.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel57.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel12.setText("Dissolved Organic Carbon:");

        jTextFieldDOC.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel59.setText("mg/L");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel57)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel58)
                        .addGap(45, 45, 45))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel31)
                            .addComponent(jLabel32)
                            .addComponent(jLabel37)
                            .addComponent(jLabel54)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(jTextFieldPH, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel50))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldConductivity, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldWatORP, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldSEDORP, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel51)
                                    .addComponent(jLabel53)
                                    .addComponent(jLabel55)))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(jTextFieldDissOxygen, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel56))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(jTextFieldDOC, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel59)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jLabel52))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jLabel52))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jTextFieldPH, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel50))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel51)
                            .addComponent(jLabel31))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldConductivity, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel32))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldDissOxygen, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel56)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldDOC, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel59)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel37)
                            .addComponent(jTextFieldWatORP, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel55))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel54)
                            .addComponent(jTextFieldSEDORP, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel53))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel57)
                    .addComponent(jLabel58))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel12.setBackground(new java.awt.Color(204, 204, 204));
        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.MatteBorder(null), "General informations", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        jTextFieldDOI.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel25.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel25.setText("DOI:");

        jLabel30.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel30.setText("Total dose:");

        jTextFieldTotDose.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel16.setText("mg/L");

        jLabel47.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel47.setText("Injection mode: ");

        jComboBoxInjection.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Without injection", "Monodose", "Pulse" }));
        jComboBoxInjection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxInjectionActionPerformed(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel29.setText("Type of ecosystem:   ");

        jComboBoxEcosystem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pond", "River", "Estuarine" }));

        jTextFieldTotTime.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel76.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel76.setText("Total time:");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldDOI, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldTotDose, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addGap(15, 15, 15)
                .addComponent(jLabel76)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldTotTime, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel29)
                .addGap(3, 3, 3)
                .addComponent(jComboBoxEcosystem, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel47)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxInjection, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jTextFieldDOI, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30)
                    .addComponent(jTextFieldTotDose, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel47)
                        .addComponent(jComboBoxInjection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel76)
                        .addComponent(jTextFieldTotTime, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel29)
                        .addComponent(jComboBoxEcosystem, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(69, 69, 69))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "DOI", "Nanoparticle", "Total dose", "Injection mode", "Ecosystem", "Total time", "Measure time", "PH", "Temperature", "Conductivity", "Dissolved oxygen", "ORP water", "ORP sediment", "Concentration water", "Concentration sediment", "Dissolved concentration", "TBARS", "TAOC", "Algae", "Bacteria"
            }
        )
        //make the jtable cell not editable
        {public boolean isCellEditable(int row, int column){return false;}}
    );
    jTable1.setGridColor(new java.awt.Color(204, 255, 0));

    jTable1.setSelectionBackground(new java.awt.Color(0, 153, 0));

    jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jTable1MouseClicked(evt);
        }
    });
    jScrollPane1.setViewportView(jTable1);

    jButtonAddMesocosm.setBackground(new java.awt.Color(204, 204, 204));
    jButtonAddMesocosm.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
    jButtonAddMesocosm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaNanoSerenade/image/save_button.png"))); // NOI18N
    jButtonAddMesocosm.setBorderPainted(false);
    jButtonAddMesocosm.setContentAreaFilled(false);
    jButtonAddMesocosm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jButtonAddMesocosm.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonAddMesocosmActionPerformed(evt);
        }
    });

    jButtonRemoveMesocosm.setBackground(new java.awt.Color(204, 204, 204));
    jButtonRemoveMesocosm.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
    jButtonRemoveMesocosm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaNanoSerenade/image/remove_button.png"))); // NOI18N
    jButtonRemoveMesocosm.setBorderPainted(false);
    jButtonRemoveMesocosm.setContentAreaFilled(false);
    jButtonRemoveMesocosm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jButtonRemoveMesocosm.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonRemoveMesocosmActionPerformed(evt);
        }
    });

    jButtonEditMesocosm.setBackground(new java.awt.Color(204, 204, 204));
    jButtonEditMesocosm.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
    jButtonEditMesocosm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaNanoSerenade/image/edit_button.png"))); // NOI18N
    jButtonEditMesocosm.setBorderPainted(false);
    jButtonEditMesocosm.setContentAreaFilled(false);
    jButtonEditMesocosm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jButtonEditMesocosm.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonEditMesocosmActionPerformed(evt);
        }
    });

    jButtonClearMesocosm.setBackground(new java.awt.Color(204, 204, 204));
    jButtonClearMesocosm.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
    jButtonClearMesocosm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaNanoSerenade/image/reset_button.png"))); // NOI18N
    jButtonClearMesocosm.setBorderPainted(false);
    jButtonClearMesocosm.setContentAreaFilled(false);
    jButtonClearMesocosm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jButtonClearMesocosm.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonClearMesocosmActionPerformed(evt);
        }
    });

    jButtonRefreshMesocosm.setBackground(new java.awt.Color(204, 204, 204));
    jButtonRefreshMesocosm.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
    jButtonRefreshMesocosm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaNanoSerenade/image/search_button.png"))); // NOI18N
    jButtonRefreshMesocosm.setBorderPainted(false);
    jButtonRefreshMesocosm.setContentAreaFilled(false);
    jButtonRefreshMesocosm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jButtonRefreshMesocosm.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonRefreshMesocosmActionPerformed(evt);
        }
    });

    jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaNanoSerenade/image/exit_button.png"))); // NOI18N
    jButton1.setBorderPainted(false);
    jButton1.setContentAreaFilled(false);
    jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jButton1.setDefaultCapable(false);
    jButton1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton1ActionPerformed(evt);
        }
    });

    jPanel13.setBackground(new java.awt.Color(204, 204, 204));
    jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.MatteBorder(null), "Mesocosm instance informations", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

    jTextFieldName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

    jLabel27.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
    jLabel27.setText("Name:");

    jLabel77.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
    jLabel77.setText("Measure time:");

    jTextFieldMeasTime.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

    jLabel13.setText("days");

    javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
    jPanel13.setLayout(jPanel13Layout);
    jPanel13Layout.setHorizontalGroup(
        jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel13Layout.createSequentialGroup()
            .addGap(273, 273, 273)
            .addComponent(jLabel27)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(145, 145, 145)
            .addComponent(jLabel77)
            .addGap(18, 18, 18)
            .addComponent(jTextFieldMeasTime, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(jLabel13)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel13Layout.setVerticalGroup(
        jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel13Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel27)
                .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel77)
                .addComponent(jTextFieldMeasTime, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel13))
            .addContainerGap(17, Short.MAX_VALUE))
    );

    jButtonImport.setText("import");
    jButtonImport.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonImportActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(5, 5, 5)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(48, 48, 48)
                                    .addComponent(jButtonImport)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonAddMesocosm, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(45, 45, 45)
                                    .addComponent(jButtonEditMesocosm, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(52, 52, 52)
                                    .addComponent(jButtonRemoveMesocosm, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(52, 52, 52)
                                    .addComponent(jButtonClearMesocosm, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(56, 56, 56)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jButtonRefreshMesocosm, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(82, 82, 82))
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1272, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap(17, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(8, 8, 8)
            .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(6, 6, 6)
            .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(6, 6, 6)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addComponent(jButtonRefreshMesocosm))
                .addComponent(jButtonClearMesocosm)
                .addComponent(jButtonRemoveMesocosm)
                .addComponent(jButtonEditMesocosm)
                .addComponent(jButtonAddMesocosm)
                .addComponent(jButtonImport))
            .addGap(11, 11, 11)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
            .addGap(33, 33, 33))
    );

    jMenu1.setText("File");
    jMenuBar1.add(jMenu1);

    jMenu2.setText("Edit");
    jMenuBar1.add(jMenu2);

    jMenu3.setText("Help");

    jMenu5.setText("Tutorial");
    jMenu3.add(jMenu5);
    jMenu3.add(jSeparator1);

    jMenu4.setText("About the SERENADE");
    jMenu3.add(jMenu4);

    jMenuBar1.add(jMenu3);

    setJMenuBar(jMenuBar1);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addContainerGap())
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldTAOCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTAOCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTAOCActionPerformed

    private void jTextFieldPHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPHActionPerformed

    private void jButtonAddMesocosmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddMesocosmActionPerformed
        //get data from jtextfields
       try{
            String doi = jTextFieldDOI.getText().trim();
            String nanoparticle = jTextFieldName.getText().trim();
            float totaldose = Float.parseFloat(jTextFieldTotDose.getText().trim());
            String injectionMode = jComboBoxInjection.getSelectedItem().toString().trim();
            String ecosystem = jComboBoxEcosystem.getSelectedItem().toString().trim();
            int totalTime = Integer.parseInt(jTextFieldTotTime.getText().trim());
            int measureTime = Integer.parseInt(jTextFieldMeasTime.getText().trim());
            float ph = Float.parseFloat(jTextFieldPH.getText().trim());
            float temperature = Float.parseFloat(jTextFieldTemp.getText().trim());
            float conductivity = Float.parseFloat(jTextFieldConductivity.getText().trim());
            float dissoveldOxigen = Float.parseFloat(jTextFieldDissOxygen.getText().trim());
            float orpWater = Float.parseFloat(jTextFieldWatORP.getText().trim());
            float orpSediment = Float.parseFloat(jTextFieldSEDORP.getText().trim());
            float concentrationWater = Float.parseFloat(jTextFieldWatConcentration.getText().trim());
            float concentrationSediment = Float.parseFloat(jTextFieldSedConcentration.getText().trim());
            float dissolvedConcentration = Float.parseFloat(jTextFieldDissConcentration.getText().trim());
            float tbars = Float.parseFloat(jTextFieldTBARS.getText().trim());
            float taoc = Float.parseFloat(jTextFieldTAOC.getText().trim());
            float algae = Float.parseFloat(jTextFieldAlgae.getText().trim());
            float bacteria = Float.parseFloat(jTextFieldBacteria.getText().trim());
            
        
            if(mesocosm.addMesocosm(doi, nanoparticle, totaldose, injectionMode, ecosystem, totalTime, measureTime, ph, temperature, conductivity, dissoveldOxigen, orpWater, orpSediment, concentrationWater, concentrationSediment, dissolvedConcentration, tbars, taoc, algae, bacteria))
            {
                JOptionPane.showMessageDialog(rootPane, "New Mesocosm added Successfully", "Add Mesocosm", JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(rootPane, "Mesocosm Not Added ", "Add Mesocosm Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch(NumberFormatException ex)
              {
                JOptionPane.showMessageDialog(rootPane, ex.getMessage() + "Enter The Mesocosm ID", "Mesocosm ID Error", JOptionPane.ERROR_MESSAGE);
            }
       //clear the JTable first
       jTable1.setModel(new DefaultTableModel(null, new Object[]{"ID", "DOI", "Nanoparticle", "Total dose", "Injection mode", "Ecosystem", "Total time", "Measure time", "PH", "Temperature", "Conductivity", "Dissolved oxygen", "ORP water", "ORP sediment", "Concentration water", "Concentration sediment", "Dissolved concentration", "TBARS", "TAOC", "Algae", "Bacteria"}));
       
        // then populate the JTable
        mesocosm.fillMesocosmJTable(jTable1);
    }//GEN-LAST:event_jButtonAddMesocosmActionPerformed
    
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {                                     
        //display the selected row data in the jtextfields
        
        //get the jlabel model 
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                
        // get the selected row index
        int rIndex = jTable1.getSelectedRow();
        
        //display data 
        
        jTextFieldDOI.setText(model.getValueAt(rIndex, 1).toString());
        jTextFieldName.setText(model.getValueAt(rIndex, 7).toString());
        jTextFieldTotDose.setText(model.getValueAt(rIndex, 3).toString());
        String injectionMode = jComboBoxInjection.getSelectedItem().toString();
        String ecosystem = jComboBoxEcosystem.getSelectedItem().toString();
        jTextFieldTotTime.setText(model.getValueAt(rIndex, 2).toString());
        jTextFieldMeasTime.setText(model.getValueAt(rIndex, 6).toString());
        jTextFieldPH.setText(model.getValueAt(rIndex, 8).toString());
        jTextFieldTemp.setText(model.getValueAt(rIndex, 9).toString());
        jTextFieldConductivity.setText(model.getValueAt(rIndex, 10).toString());
        jTextFieldDissOxygen.setText(model.getValueAt(rIndex, 11).toString());
        jTextFieldWatORP.setText(model.getValueAt(rIndex, 12).toString());
        jTextFieldSEDORP.setText(model.getValueAt(rIndex, 13).toString());
        jTextFieldWatConcentration.setText(model.getValueAt(rIndex, 14).toString());
        jTextFieldSedConcentration.setText(model.getValueAt(rIndex, 15).toString());
        jTextFieldDissConcentration.setText(model.getValueAt(rIndex, 16).toString());
        jTextFieldTBARS.setText(model.getValueAt(rIndex, 17).toString());
        jTextFieldTAOC.setText(model.getValueAt(rIndex, 18).toString());
        jTextFieldAlgae.setText(model.getValueAt(rIndex, 19).toString());
        jTextFieldBacteria.setText(model.getValueAt(rIndex, 20).toString());
               
    }
    
    private void jButtonClearMesocosmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearMesocosmActionPerformed
        // remove text from all jTextfields
        jTextFieldAlgae.setText("");
        jTextFieldBacteria.setText("");
        jTextFieldConductivity.setText("");
        jTextFieldDOC.setText("");
        jTextFieldDOI.setText("");
        jTextFieldDissConcentration.setText("");
        jTextFieldDissOxygen.setText("");
        jTextFieldMeasTime.setText("");
        jTextFieldName.setText("");
        jTextFieldPH.setText("");
        jTextFieldSEDORP.setText("");
        jTextFieldSedConcentration.setText("");
        jTextFieldSedSpeciation.setText("");
        jTextFieldSize.setText("");
        jTextFieldTAOC.setText("");
        jTextFieldTBARS.setText("");
        jTextFieldTemp.setText("");
        jTextFieldTotDose.setText("");
        jTextFieldTotTime.setText("");
        jTextFieldWatConcentration.setText("");
        jTextFieldWatORP.setText("");
        jTextFieldWatSpeciation.setText("");
        
    }//GEN-LAST:event_jButtonClearMesocosmActionPerformed

    private void jButtonRefreshMesocosmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefreshMesocosmActionPerformed
        SearchMesocosmsForm searchMesocosmForm = new SearchMesocosmsForm();
        searchMesocosmForm.setVisible(true);
        searchMesocosmForm.pack();
        searchMesocosmForm.setLocationRelativeTo(null);
        searchMesocosmForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jButtonRefreshMesocosmActionPerformed

    private void jButtonEditMesocosmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditMesocosmActionPerformed
        // EDIT THE SELECTED Mesocosm
        
        //Récupérer le numéro de la ligne tout en l'affichant
        int row = jTable1.getSelectedRow();
        //je récupère la valeur de la colonne ID
        String value = (jTable1.getModel().getValueAt(row, 0).toString());
        //je parse la valeur de la première colonne pour récupérer mes trois id (ide, ids et idm)
        String[] parts = value.split("_");
        //je récupère le 1er élément correspondant à l'IDE de la ligne du table
        long rowIdE =  Long.parseLong(parts[0]);
        //je récupère le 2ème élément correspondant à l'IDS de la ligne du table
        long rowIdS =  Long.parseLong(parts[1]);
        //je récupère le 3ème élément correspondant à l'IDM de la ligne du table
        long rowIdM =  Long.parseLong(parts[2]);
        
        
        
        //System.out.println(rowIdE);
        
        //System.out.println(rowIdS);
        
        //System.out.println(rowIdM);
        
        //System.out.println(row);
        
       // System.out.println(value);
        
        //get data from the fields
        
        
         try{
            String doi = jTextFieldDOI.getText();
            String nanoparticle = jTextFieldName.getText();
            float totaldose = Float.parseFloat(jTextFieldTotDose.getText());
            String injectionMode = jComboBoxInjection.getSelectedItem().toString();
            String ecosystem = jComboBoxEcosystem.getSelectedItem().toString();
            int totalTime = Integer.parseInt(jTextFieldTotTime.getText());
            int measureTime = Integer.parseInt(jTextFieldMeasTime.getText());
            float ph = Float.parseFloat(jTextFieldPH.getText());
            float temperature = Float.parseFloat(jTextFieldTemp.getText());
            float conductivity = Float.parseFloat(jTextFieldConductivity.getText());
            float dissoveldOxigen = Float.parseFloat(jTextFieldDissOxygen.getText());
            float orpWater = Float.parseFloat(jTextFieldWatORP.getText());
            float orpSediment = Float.parseFloat(jTextFieldSEDORP.getText());
            float concentrationWater = Float.parseFloat(jTextFieldWatConcentration.getText());
            float concentrationSediment = Float.parseFloat(jTextFieldSedConcentration.getText());
            float dissolvedConcentration = Float.parseFloat(jTextFieldDissConcentration.getText());
            float tbars = Float.parseFloat(jTextFieldTBARS.getText());
            float taoc = Float.parseFloat(jTextFieldTAOC.getText());
            float algae = Float.parseFloat(jTextFieldAlgae.getText());
            float bacteria = Float.parseFloat(jTextFieldBacteria.getText());
        
          
                      
         if(mesocosm.editMesocosm(rowIdE, rowIdS, rowIdM, doi, nanoparticle, totaldose, injectionMode, ecosystem, totalTime, measureTime, ph, temperature, conductivity, dissoveldOxigen, orpWater, orpSediment, concentrationWater, concentrationSediment, dissolvedConcentration, tbars, taoc, algae, bacteria))
            {
                JOptionPane.showMessageDialog(rootPane, "Mesocosm Data Updated Successfully", "Edit Mesocosm", JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(rootPane, "Mesocosm Data Not Updated ", "Edit Mesocosm Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch(NumberFormatException ex)
              {
                JOptionPane.showMessageDialog(rootPane, ex.getMessage() + "Enter The Mesocosm ID", "Mesocosm ID Error", JOptionPane.ERROR_MESSAGE);
            }
          //clear the JTable first
       jTable1.setModel(new DefaultTableModel(null, new Object[]{"ID", "DOI", "Nanoparticle", "Total dose", "Injection mode", "Ecosystem", "Total time", "Measure time", "PH", "Temperature", "Conductivity", "Dissolved oxygen", "ORP water", "ORP sediment", "Concentration water", "Concentration sediment", "Dissolved concentration", "TBARS", "TAOC", "Algae", "Bacteria"}));
       
        // then populate the JTable
        mesocosm.fillMesocosmJTable(jTable1);
    }//GEN-LAST:event_jButtonEditMesocosmActionPerformed

    private void jButtonRemoveMesocosmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveMesocosmActionPerformed
        String nanoparticle = jTextFieldName.getText();
        int measureTime = Integer.parseInt(jTextFieldMeasTime.getText());
        int opt = JOptionPane.showConfirmDialog(null, "The deletion of the mesocosm "+ nanoparticle +" will cause the deletion of all its instantiation at the measure time " +measureTime+ ". Are you sure you want to delete all these instances? ", "Remove Mesocosm", JOptionPane.YES_NO_OPTION);
        if(opt==0){
         //Récupérer le numéro de la ligne tout en l'affichant
        int row = jTable1.getSelectedRow();
        //je récupère la valeur de la colonne ID
        String value = (jTable1.getModel().getValueAt(row, 0).toString());
        //je parse la valeur de la première colonne pour récupérer mes trois id (ide, ids et idm)
        String[] parts = value.split("_");
        //je récupère le 1er élément correspondant à l'IDE de la ligne du table
        long rowIdE =  Long.parseLong(parts[0]);
        //je récupère le 2ème élément correspondant à l'IDS de la ligne du table
        long rowIdS =  Long.parseLong(parts[1]);
        //je récupère le 3ème élément correspondant à l'IDM de la ligne du table
        long rowIdM =  Long.parseLong(parts[2]);
        
        try{
                    String doi = jTextFieldDOI.getText();
                    
                    if(mesocosm.removeMesocosm(rowIdE, rowIdS, rowIdM))
                        {
                            JOptionPane.showMessageDialog(rootPane, "Mesocosm Deleted Successfully", "Remove Mesocosm", JOptionPane.INFORMATION_MESSAGE);
                    }
                    else{
                            JOptionPane.showMessageDialog(rootPane, "Mesocosm Not Deleted ", "Remove Mesocosm Error", JOptionPane.ERROR_MESSAGE);
                        }
               }
              catch(NumberFormatException ex)
              {
                JOptionPane.showMessageDialog(rootPane, ex.getMessage() + "Enter The Mesocosm Id ", "Mesocosm ID Error", JOptionPane.ERROR_MESSAGE);
            }
        //clear the JTable first
       jTable1.setModel(new DefaultTableModel(null, new Object[]{"ID", "DOI", "Nanoparticle", "Total dose", "Injection mode", "Ecosystem", "Total time", "Measure time", "PH", "Temperature", "Conductivity", "Dissolved oxygen", "ORP water", "ORP sediment", "Concentration water", "Concentration sediment", "Dissolved concentration", "TBARS", "TAOC", "Algae", "Bacteria"}));
       
        // then populate the JTable
        mesocosm.fillMesocosmJTable(jTable1);
        }
        
    }//GEN-LAST:event_jButtonRemoveMesocosmActionPerformed

    private void jComboBoxInjectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxInjectionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxInjectionActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextFieldWatSpeciationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldWatSpeciationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldWatSpeciationActionPerformed

    private void jTextFieldTBARSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTBARSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTBARSActionPerformed

    private void jButtonImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImportActionPerformed
        OpenFile of = new OpenFile();
        
        
        try{
            of.PickMe();
        }catch (Exception e){
            e.printStackTrace();
        }
        ///textArea.setText(of.sb.toString());
        
    }//GEN-LAST:event_jButtonImportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageMesocosmsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageMesocosmsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageMesocosmsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageMesocosmsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageMesocosmsForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAddMesocosm;
    private javax.swing.JButton jButtonClearMesocosm;
    private javax.swing.JButton jButtonEditMesocosm;
    private javax.swing.JButton jButtonImport;
    private javax.swing.JButton jButtonRefreshMesocosm;
    private javax.swing.JButton jButtonRemoveMesocosm;
    private javax.swing.JComboBox<String> jComboBoxEcosystem;
    private javax.swing.JComboBox<String> jComboBoxInjection;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldAlgae;
    private javax.swing.JTextField jTextFieldBacteria;
    private javax.swing.JTextField jTextFieldConductivity;
    private javax.swing.JTextField jTextFieldDOC;
    private javax.swing.JTextField jTextFieldDOI;
    private javax.swing.JTextField jTextFieldDissConcentration;
    private javax.swing.JTextField jTextFieldDissOxygen;
    private javax.swing.JTextField jTextFieldMeasTime;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldPH;
    private javax.swing.JTextField jTextFieldSEDORP;
    private javax.swing.JTextField jTextFieldSedConcentration;
    private javax.swing.JTextField jTextFieldSedSpeciation;
    private javax.swing.JTextField jTextFieldSize;
    private javax.swing.JTextField jTextFieldTAOC;
    private javax.swing.JTextField jTextFieldTBARS;
    private javax.swing.JTextField jTextFieldTemp;
    private javax.swing.JTextField jTextFieldTotDose;
    private javax.swing.JTextField jTextFieldTotTime;
    private javax.swing.JTextField jTextFieldWatConcentration;
    private javax.swing.JTextField jTextFieldWatORP;
    private javax.swing.JTextField jTextFieldWatSpeciation;
    // End of variables declaration//GEN-END:variables
}
