/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaNanoSerenade;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author aliay
 */
public class ManageDictionaryForm extends javax.swing.JFrame {

    
    DICTIONARY dictionary = new DICTIONARY();
    /**
     * Creates new form ManageRoomsForm
     */
    public ManageDictionaryForm() {
        initComponents();
        
         //ajout d une icone serende pour la page
          this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/javaNanoSerenade/image/lloogg_ser.png")).getImage());
        
         //populate the jtable
        dictionary.fillDictionaryJTable(jTable1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldGroup = new javax.swing.JTextField();
        jLabel52 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldParameter = new javax.swing.JTextField();
        jTextFieldItem = new javax.swing.JTextField();
        jTextFieldDictionaryID = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonRefreshDictionary = new javax.swing.JButton();
        jButtonClearDictionary = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButtonRemoveDictionary = new javax.swing.JButton();
        jButtonAddDictionary = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenu4 = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manage Dictionary");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setName(""); // NOI18N

        jPanel10.setBackground(new java.awt.Color(204, 204, 204));
        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.MatteBorder(null), "Dictionary informations", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 16))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel9.setText("Group:");

        jTextFieldGroup.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldGroupActionPerformed(evt);
            }
        });

        jLabel57.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel11.setText("Item:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel14.setText("Parameter:");

        jTextFieldParameter.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTextFieldItem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldItemActionPerformed(evt);
            }
        });

        jTextFieldDictionaryID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldDictionaryID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDictionaryIDActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel10.setText("Dictionary ID:");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel57)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1184, Short.MAX_VALUE)
                .addComponent(jLabel58)
                .addGap(45, 45, 45)
                .addComponent(jLabel52))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldDictionaryID, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldItem, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addGap(26, 26, 26)
                .addComponent(jTextFieldParameter, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldDictionaryID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10))
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9))
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11))
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldParameter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel52)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel57)
                    .addComponent(jLabel58)))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Dictionary ID", "Group", "Item", "Parameter"
            }
        )
        //make the jtable cell not editable
        {public boolean isCellEditable(int row, int column){return false;}}
    );
    jTable1.setGridColor(new java.awt.Color(204, 255, 0));

    jTable1.setSelectionBackground(new java.awt.Color(0, 153, 0));

    jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jTable1MouseClicked(evt);
        }
    });
    jScrollPane1.setViewportView(jTable1);

    jButtonRefreshDictionary.setBackground(new java.awt.Color(204, 204, 204));
    jButtonRefreshDictionary.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
    jButtonRefreshDictionary.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaNanoSerenade/image/refresh_button.png"))); // NOI18N
    jButtonRefreshDictionary.setBorderPainted(false);
    jButtonRefreshDictionary.setContentAreaFilled(false);
    jButtonRefreshDictionary.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jButtonRefreshDictionary.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonRefreshDictionaryActionPerformed(evt);
        }
    });

    jButtonClearDictionary.setBackground(new java.awt.Color(204, 204, 204));
    jButtonClearDictionary.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
    jButtonClearDictionary.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaNanoSerenade/image/reset_button.png"))); // NOI18N
    jButtonClearDictionary.setBorderPainted(false);
    jButtonClearDictionary.setContentAreaFilled(false);
    jButtonClearDictionary.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jButtonClearDictionary.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonClearDictionaryActionPerformed(evt);
        }
    });

    jButton10.setBackground(new java.awt.Color(204, 204, 204));
    jButton10.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
    jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaNanoSerenade/image/edit_button.png"))); // NOI18N
    jButton10.setBorderPainted(false);
    jButton10.setContentAreaFilled(false);
    jButton10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jButton10.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton10ActionPerformed(evt);
        }
    });

    jButtonRemoveDictionary.setBackground(new java.awt.Color(204, 204, 204));
    jButtonRemoveDictionary.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
    jButtonRemoveDictionary.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaNanoSerenade/image/remove_button.png"))); // NOI18N
    jButtonRemoveDictionary.setBorderPainted(false);
    jButtonRemoveDictionary.setContentAreaFilled(false);
    jButtonRemoveDictionary.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jButtonRemoveDictionary.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonRemoveDictionaryActionPerformed(evt);
        }
    });

    jButtonAddDictionary.setBackground(new java.awt.Color(204, 204, 204));
    jButtonAddDictionary.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
    jButtonAddDictionary.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaNanoSerenade/image/save_button.png"))); // NOI18N
    jButtonAddDictionary.setBorderPainted(false);
    jButtonAddDictionary.setContentAreaFilled(false);
    jButtonAddDictionary.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jButtonAddDictionary.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonAddDictionaryActionPerformed(evt);
        }
    });

    jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaNanoSerenade/image/exit_button.png"))); // NOI18N
    jButton1.setBorderPainted(false);
    jButton1.setContentAreaFilled(false);
    jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jButton1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton1ActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(108, 108, 108)
                    .addComponent(jButtonAddDictionary, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(34, 34, 34)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(37, 37, 37)
                    .addComponent(jButtonRemoveDictionary, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(46, 46, 46)
                    .addComponent(jButtonClearDictionary, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(58, 58, 58)
                    .addComponent(jButtonRefreshDictionary, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(70, 70, 70)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(61, 61, 61)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1168, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap(28, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonRefreshDictionary, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonClearDictionary, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton10, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonRemoveDictionary)
                    .addComponent(jButtonAddDictionary))
                .addComponent(jButton1))
            .addGap(18, 18, 18)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(78, Short.MAX_VALUE))
    );

    jMenu1.setText("File");
    jMenuBar1.add(jMenu1);

    jMenu2.setText("Edit");
    jMenuBar1.add(jMenu2);

    jMenu3.setText("Help");

    jMenu5.setText("Tutorial");
    jMenu3.add(jMenu5);
    jMenu3.add(jSeparator1);

    jMenu4.setText("About the SERENADE");
    jMenu3.add(jMenu4);

    jMenuBar1.add(jMenu3);

    setJMenuBar(jMenuBar1);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldGroupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldGroupActionPerformed

    private void jTextFieldItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldItemActionPerformed

    private void jButtonAddDictionaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddDictionaryActionPerformed
          //add a new cient
        
        //get data from the fields
        String group = jTextFieldGroup.getText();
        String item = jTextFieldItem.getText();
        String parameter = jTextFieldParameter.getText();
        
        
        if(group.trim().equals("") || item.trim().equals("") || parameter.trim().equals(""))
        {
            JOptionPane.showMessageDialog(rootPane, "Required Fields -> Group + Item + Parameter.", "Empty Fields", JOptionPane.WARNING_MESSAGE);
        }
        else {
            if(dictionary.addDictionary(group, item, parameter))
            {
                JOptionPane.showMessageDialog(rootPane, "New Dictionary added Successfully", "Add Dictionary", JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(rootPane, "Dictionary Not Added ", "Add Dictionary Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        //clear the JTable first
       jTable1.setModel(new DefaultTableModel(null, new Object[]{"Dictionary ID", "Group", "Item", "Parameter"}));
       
        // then populate the JTable
        dictionary.fillDictionaryJTable(jTable1);
    }//GEN-LAST:event_jButtonAddDictionaryActionPerformed
 private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {                                     
        //display the selected row data in the jtextfields
        
        //get the jlabel model 
        DefaultTableModel model = (DefaultTableModel )jTable1.getModel();
                
        // get the selected row index
        int rIndex = jTable1.getSelectedRow();
        
        //display data 
        jTextFieldDictionaryID.setText(model.getValueAt(rIndex, 0).toString());
        jTextFieldGroup.setText(model.getValueAt(rIndex, 1).toString());
        jTextFieldItem.setText(model.getValueAt(rIndex, 2).toString());
        jTextFieldParameter.setText(model.getValueAt(rIndex, 3).toString());
    }                              
 
    private void jButtonClearDictionaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearDictionaryActionPerformed
        // remove text from all jTextfields
        jTextFieldDictionaryID.setText("");
        jTextFieldGroup.setText("");
        jTextFieldItem.setText("");
        jTextFieldParameter.setText("");
        
    }//GEN-LAST:event_jButtonClearDictionaryActionPerformed

    private void jTextFieldDictionaryIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDictionaryIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDictionaryIDActionPerformed

    private void jButtonRefreshDictionaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefreshDictionaryActionPerformed
        //clear the JTable first
       jTable1.setModel(new DefaultTableModel(null, new Object[]{"Dictionary ID", "Group", "Item", "Parameter"}));
       
        // then populate the JTable
        dictionary.fillDictionaryJTable(jTable1);
    }//GEN-LAST:event_jButtonRefreshDictionaryActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        //get data from the fields
        int dictionaryID = 0;
        String group = jTextFieldGroup.getText();
        String item = jTextFieldItem.getText();
        String parameter = jTextFieldParameter.getText();
        
          if(group.trim().equals("") || item.trim().equals("") || parameter.trim().equals(""))
        {
            JOptionPane.showMessageDialog(rootPane, "Required Fields -> Group + Item + Parameter.", "Empty Fields", JOptionPane.WARNING_MESSAGE);
        }
        else {
              
              try{
                    dictionaryID = Integer.valueOf(jTextFieldDictionaryID.getText());
                    
                    if(dictionary.editDictionary(dictionaryID, group, item, parameter))
                        {
                            JOptionPane.showMessageDialog(rootPane, "Dictionary Data Updated Successfully", "Edit Dictionary", JOptionPane.INFORMATION_MESSAGE);
                    }else{
                            JOptionPane.showMessageDialog(rootPane, "Dictionary Data Not Updated ", "Edit Dictionary Error", JOptionPane.ERROR_MESSAGE);
                        }
               }
              catch(NumberFormatException ex)
              {
                JOptionPane.showMessageDialog(rootPane, ex.getMessage() + "Enter The Dictionary Id ", "Dictionary ID Error", JOptionPane.ERROR_MESSAGE);
            }
                      
            
        }
          //clear the JTable first
       jTable1.setModel(new DefaultTableModel(null, new Object[]{"Dictionary ID", "Group", "Item", "Parameter"}));
       
        // then populate the JTable
        dictionary.fillDictionaryJTable(jTable1);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButtonRemoveDictionaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveDictionaryActionPerformed
         // Delete the selected client
        try{
                    int dictionaryID = Integer.valueOf(jTextFieldDictionaryID.getText());
                    
                    if(dictionary.removeDictionary(dictionaryID))
                        {
                            JOptionPane.showMessageDialog(rootPane, "Dictionary Deleted Successfully", "Remove Dictionary", JOptionPane.INFORMATION_MESSAGE);
                    }
                    else{
                            JOptionPane.showMessageDialog(rootPane, "Dictionary Not Deleted ", "Remove Dictionary Error", JOptionPane.ERROR_MESSAGE);
                        }
               }
              catch(NumberFormatException ex)
              {
                JOptionPane.showMessageDialog(rootPane, ex.getMessage() + "Enter The Dictionary Id", "Dictionary ID Error", JOptionPane.ERROR_MESSAGE);
            }
        //clear the JTable first
       jTable1.setModel(new DefaultTableModel(null, new Object[]{"Dictionary ID", "Group", "Item", "Parameter"}));
       
        // then populate the JTable
        dictionary.fillDictionaryJTable(jTable1);
    }//GEN-LAST:event_jButtonRemoveDictionaryActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageDictionaryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageDictionaryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageDictionaryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageDictionaryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageDictionaryForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButtonAddDictionary;
    private javax.swing.JButton jButtonClearDictionary;
    private javax.swing.JButton jButtonRefreshDictionary;
    private javax.swing.JButton jButtonRemoveDictionary;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldDictionaryID;
    private javax.swing.JTextField jTextFieldGroup;
    private javax.swing.JTextField jTextFieldItem;
    private javax.swing.JTextField jTextFieldParameter;
    // End of variables declaration//GEN-END:variables
}
